/* eslint-env browser */

import {
	isCoverflow,
	isPerspective,
	isCard,
	showPeek,
	isAutoplayEnabled,
	showSlidesPerView,
	showGap,
	showCenterMode,
	showLoop,
	showAutoplay,
	showEasing,
	showAutoplaySpeed,
	showAutoplaySettings,
	showCenterScale
} from './predicates';

const DIRECTION_OPTIONS = [
	{ value: 'right', label: 'Right' },
	{ value: 'left', label: 'Left' }
];

const EFFECT_OPTIONS = [
	{ value: 'coverflow', label: 'Coverflow 3D' },
	{ value: 'card', label: 'Card 3D' },
	{ value: 'perspective', label: 'Perspective' },
	{ value: 'slide', label: 'Slide' },
	{ value: 'marquee', label: 'Marquee (Continuous Scroll)' }
];

const EASING_OPTIONS = [
	{ value: 'power1', label: 'Power 1 (Smooth)' },
	{ value: 'power2', label: 'Power 2 (Default)' },
	{ value: 'power3', label: 'Power 3 (Strong)' },
	{ value: 'power4', label: 'Power 4 (Snappy)' },
	{ value: 'elastic', label: 'Elastic' },
	{ value: 'back', label: 'Back' },
	{ value: 'bounce', label: 'Bounce' },
	{ value: 'expo', label: 'Expo' }
];


const config = {
	anchorKey: 'aae-section-aae-slider',

	// The slider properties share the 'aae_ns_' prefix, matching the Schema mapping.
	bindPrefix: 'aae_ns_',

	// Every field carries a `tab` ('general' | 'advanced'); ResponsiveSection
	// groups them into an outer tab bar. General = the everyday layout/playback
	// controls; Advanced = effect-specific 3D math and fine-tuning.
	fields: [
		// ---- General ----------------------------------------------------------
		{
			tab: 'general',
			bind: 'effect',
			label: 'Slider Effect',
			control: 'select',
			options: EFFECT_OPTIONS,
			responsive: true,
			defaultValue: 'slide',
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'general',
			bind: 'slides_per_view',
			label: 'Slides Per View',
			control: 'slider',
			responsive: true,
			defaultValue: 3,
			min: 1,
			max: 15,
			when: showSlidesPerView,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'general',
			bind: 'gap',
			label: 'Slide Gap (px)',
			control: 'slider',
			responsive: true,
			defaultValue: 0,
			min: 0,
			max: 100,
			when: showGap,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'general',
			bind: 'slide_height',
			label: 'Slide Height (px)',
			control: 'slider',
			responsive: true,
			defaultValue: 0,
			min: 0,
			max: 1000,
			when: showGap,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'general',
			bind: 'center_mode',
			label: 'Center Mode',
			control: 'switch',
			responsive: true,
			defaultValue: false,
			when: showCenterMode,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'general',
			bind: 'center_scale',
			label: 'Center Scale',
			control: 'slider',
			responsive: true,
			defaultValue: 0.85,
			min: 0.1,
			max: 1.0,
			step: 0.05,
			when: showCenterScale,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'general',
			bind: 'loop',
			label: 'Infinite Loop',
			control: 'switch',
			responsive: true,
			defaultValue: false,
			when: showLoop,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'general',
			bind: 'overflow',
			label: 'Slider Overflow',
			control: 'select',
			options: [
				{ value: 'visible', label: 'Visible' },
				{ value: 'hidden', label: 'Hidden' }
			],
			responsive: true,
			defaultValue: 'visible',
			help: 'Set to Visible so Prev/Next arrows, pagination, or 3D cards outside the container boundaries are not clipped.',
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'general',
			bind: 'autoplay',
			label: 'Autoplay',
			control: 'switch',
			responsive: true,
			defaultValue: false,
			when: showAutoplay,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'general',
			bind: 'autoplay_speed',
			label: 'Autoplay Speed (ms)',
			control: 'number',
			responsive: true,
			defaultValue: 3000,
			when: showAutoplaySpeed,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'general',
			bind: 'autoplay_delay',
			label: 'Start Delay (ms)',
			control: 'number',
			responsive: true,
			defaultValue: 0,
			when: showAutoplaySpeed,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'general',
			bind: 'autoplay_direction',
			label: 'Autoplay Direction',
			control: 'select',
			responsive: true,
			options: DIRECTION_OPTIONS,
			defaultValue: 'right',
			when: showAutoplaySettings,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'general',
			bind: 'pause_on_hover',
			label: 'Pause on Hover',
			control: 'switch',
			responsive: true,
			defaultValue: true,
			when: showAutoplaySettings,
			play_group: 'aae_ns_',
			live_change: true,
		},

		// ---- Advanced ---------------------------------------------------------
		{
			tab: 'advanced',
			bind: 'peek',
			label: 'Peek %',
			control: 'slider',
			responsive: true,
			// Default 0: no peek unless the user explicitly sets it, so a plain
			// N-per-view slider fills edge-to-edge instead of leaking a sliver.
			defaultValue: 0,
			min: 0,
			max: 20,
			step: 1,
			when: showPeek,
			help: 'Shows a sliver of the adjacent slides. If Peek doesn\'t look right, set the Slider Track element\'s padding to 0 (Track → Style → Spacing) — leftover padding shrinks the slide area and throws off the peek math.',
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'advanced',
			bind: 'easing',
			label: 'Slider Easing',
			control: 'select',
			options: EASING_OPTIONS,
			responsive: true,
			defaultValue: 'power2',
			when: showEasing,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'advanced',
			bind: 'transition_speed',
			label: 'Transition Speed (ms)',
			control: 'number',
			responsive: true,
			defaultValue: 680,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'advanced',
			bind: 'cf_rotate',
			label: 'Rotate (deg)',
			control: 'slider',
			responsive: true,
			defaultValue: 45,
			min: 0,
			max: 90,
			step: 5,
			when: isCoverflow,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'advanced',
			bind: 'cf_depth',
			label: 'Depth (px)',
			control: 'slider',
			responsive: true,
			defaultValue: 100,
			min: 0,
			max: 400,
			step: 10,
			when: isCoverflow,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'advanced',
			bind: 'card_scale',
			label: 'Card Scale',
			control: 'number',
			responsive: true,
			defaultValue: 0.88,
			step: 0.01,
			when: isCard,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'advanced',
			bind: 'card_tilt',
			label: 'Card Tilt',
			control: 'number',
			responsive: true,
			defaultValue: 20,
			when: isCard,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'advanced',
			bind: 'perspective_rotate',
			label: 'Perspective Rotate',
			control: 'number',
			responsive: true,
			defaultValue: 50,
			when: isPerspective,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'advanced',
			bind: 'perspective_depth',
			label: 'Perspective Depth',
			control: 'number',
			responsive: true,
			defaultValue: 250,
			when: isPerspective,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'advanced',
			bind: 'perspective_offset',
			label: '3D Pull In (%)',
			control: 'number',
			responsive: true,
			defaultValue: 18,
			when: isPerspective,
			play_group: 'aae_ns_',
			live_change: true,
		},
		{
			tab: 'advanced',
			bind: 'perspective',
			label: '3D Perspective (px)',
			control: 'number',
			responsive: true,
			defaultValue: 1200,
			when: isPerspective,
			play_group: 'aae_ns_',
			live_change: true,
		}
	]
};

export default config;
