<?php
/**
 * Atomic widget DASHBOARD CARD metadata.
 *
 * One entry per atomic widget the dashboard can offer: label, description,
 * icon, category, order, the PRO badge and the demo/doc links. This is the
 * list `get_dashboard_config()` renders and `assert_registry_integrity()`
 * diffs against `get_available_widgets()`.
 *
 * It lives in its own file, and is `require`d on first read rather than built
 * in the constructor, because NOTHING on a visitor's request asks for it:
 * `is_widget_active()` answers from the saved option and the parent map, and
 * registration reads `get_available_widgets()`, which is a different list.
 * Every reader of THIS list -- the dashboard payload, the widget parts, the
 * two option writers, the import enabler, the opt-in signal, the add-on's
 * usage scan and diagnostics -- runs in wp-admin. Kept in the class body it
 * was 80 KB of PHP parsed on every front-end, REST and cron request to build
 * an array none of them would read.
 *
 * ADDING A WIDGET: an entry here AND one in `build_available_widgets()` are
 * both required. Missing here, the widget registers but no card can ever
 * switch it on; missing there, the card exists and registers nothing. Under
 * WP_DEBUG `assert_registry_integrity()` error_log()s either drift.
 *
 * @package AnimationAddonsForElementor
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return [

			/*
			 * Menu renders an EXISTING WordPress menu (wp_get_nav_menus() picker +
			 * wp_nav_menu()) styled through flat props. It is not a duplicate of
			 * aae-a-nav, which builds its items as separate atomic elements
			 * (nav-item / nav-sub-item / mobile-nav) that are individually
			 * styleable — so it gets its own toggle rather than being routed
			 * through WIDGET_PARENT_MAP under Nav.
			 *
			 * Was commented out (and listed in PARKED_WIDGETS) while incomplete;
			 * class, twig, css and js have all been present for a while, and with
			 * no metadata here is_widget_active() could never return true, so
			 * register_widgets() skipped it permanently.
			 */
			'aae-a-menu' => [
				'label'        => 'WP Menu',
				'description'  => 'Renders an existing WordPress menu, styled natively in Elementor V4.',
				'icon'         => 'eicon-nav-menu',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'menu',
					'nav',
					'navigation',
					'atomic',
					'gsap',
				],
				// Sits with Nav and Site Logo — it is the second of the two
				// nav/menu widgets, not a general-purpose element.
				'category'     => 'header-footer',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-post-title' => [
				'label'        => 'Post Title',
				'description'  => 'Dynamically displays the current post title natively in Elementor V4.',
				'icon'         => 'eicon-post-title',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'post',
					'title',
					'heading',
					'atomic',
					'dynamic',
				],
				'category'     => 'blog',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-search-query' => [
				'label'        => 'Search Query',
				'description'  => 'Displays the current search-results heading (query + active date/category filters).',
				'icon'         => 'eicon-search',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'search',
					'query',
					'results',
					'atomic',
					'dynamic',
				],
				'category'     => 'blog',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-post-content' => [
				'label'        => 'Post Content',
				'description'  => 'Dynamically displays the current post content natively in Elementor V4.',
				'icon'         => 'eicon-post-content',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'post',
					'content',
					'atomic',
					'dynamic',
				],
				'category'     => 'blog',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-post-excerpt' => [
				'label'        => 'Post Excerpt',
				'description'  => 'Dynamically displays the current post excerpt, limited by words, characters or a CSS line clamp.',
				'icon'         => 'eicon-post-excerpt',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'post',
					'excerpt',
					'summary',
					'atomic',
					'dynamic',
				],
				'category'     => 'blog',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-post-image' => [
				'label'        => 'Post Image',
				'description'  => 'Dynamically displays the current post featured image natively in Elementor V4.',
				'icon'         => 'eicon-featured-image',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => false,
				'keywords'     => [
					'post',
					'image',
					'featured',
					'atomic',
					'dynamic',
				],
				'category'     => 'blog',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-advance-portfolio' => [
				'is_internal'  => false,
				'label'        => 'Advanced Portfolio',
				'description'  => 'Post/project grid with a section title. Atomic port of the Pro Advanced Portfolio widget: its Portfolio Three skin is the seeded shape, and the other skins ship as presets.',
				'icon'         => 'eicon-gallery-grid',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\AdvancePortfolio\Aaeaddon_A_Advance_Portfolio',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'portfolio',
					'project',
					'work',
					'post',
					'loop',
					'grid',
					'atomic',
				],
				'category'     => 'blog',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],
			'aae-a-portfolio-title' => [
				'is_internal'  => true,
				'label'        => 'Portfolio Section Title',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\AdvancePortfolio\Aaeaddon_A_Portfolio_Title',
				'icon'         => 'eicon-heading',
				'keywords'     => [ 'portfolio', 'section', 'title' ],
				'hide_from_panel' => true,
			],
			'aae-a-portfolio-list' => [
				'is_internal'  => true,
				'label'        => 'Portfolio Posts List',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\AdvancePortfolio\Aaeaddon_A_Portfolio_List',
				'icon'         => 'eicon-gallery-grid',
				'keywords'     => [ 'portfolio', 'list', 'grid' ],
				'hide_from_panel' => true,
			],
			'aae-a-portfolio-item' => [
				'is_internal'  => true,
				'label'        => 'Portfolio Item',
				'description'  => 'Repeats once per queried post. Reads the query the Advanced Portfolio root publishes on the Render_Context stack.',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\AdvancePortfolio\Aaeaddon_A_Portfolio_Item',
				'icon'         => 'eicon-post',
				'keywords'     => [ 'portfolio', 'item', 'post' ],
				'hide_from_panel' => true,
			],
			'aae-a-portfolio-content' => [
				'is_internal'  => true,
				'label'        => 'Portfolio Content',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\AdvancePortfolio\Aaeaddon_A_Portfolio_Content',
				'icon'         => 'eicon-text-align-left',
				'keywords'     => [ 'portfolio', 'content' ],
				'hide_from_panel' => true,
			],
			'aae-a-portfolio-date' => [
				'is_internal'  => true,
				'label'        => 'Portfolio Date',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\AdvancePortfolio\Aaeaddon_A_Portfolio_Date',
				'icon'         => 'eicon-calendar',
				'keywords'     => [ 'portfolio', 'date' ],
				'hide_from_panel' => true,
			],

			'aae-a-loop-item' => [
				'is_internal'  => true,
				'label'        => 'Loop Item',
				'description'  => 'Container widget for Loop Grid items with default flex column layout.',
				'icon'         => 'eicon-container',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\LoopGrid\Aaeaddon_A_Loop_Item',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'loop',
					'item',
					'container',
					'flex',
					'column',
					'atomic',
				],
				'category'     => 'general',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
				'default_children' => [],
			],

			'aae-a-loop-layout' => [
				'is_internal'  => true,
				'label'        => 'Loop Layout',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\LoopGrid\Aaeaddon_A_Loop_Layout',
				'icon'         => 'eicon-loop-builder',
				'keywords'     => [ 'loop', 'layout' ],
				'hide_from_panel' => true,
			],
			'aae-a-loop-pagination' => [
				'is_internal'  => true,
				'label'        => 'Loop Pagination',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\LoopGrid\Aaeaddon_A_Loop_Pagination',
				'icon'         => 'eicon-ellipsis-h',
				'keywords'     => [ 'loop', 'pagination' ],
				'hide_from_panel' => true,
			],
			'aae-a-loop-prev' => [
				'is_internal'  => true,
				'label'        => 'Loop Previous',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\LoopGrid\Aaeaddon_A_Loop_Prev',
				'icon'         => 'eicon-chevron-left',
				'keywords'     => [ 'loop', 'prev', 'pagination' ],
				'hide_from_panel' => true,
			],
			'aae-a-loop-next' => [
				'is_internal'  => true,
				'label'        => 'Loop Next',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\LoopGrid\Aaeaddon_A_Loop_Next',
				'icon'         => 'eicon-chevron-right',
				'keywords'     => [ 'loop', 'next', 'pagination' ],
				'hide_from_panel' => true,
			],
			'aae-a-loop-numbers' => [
				'is_internal'  => true,
				'label'        => 'Loop Page Numbers',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\LoopGrid\Aaeaddon_A_Loop_Numbers',
				'icon'         => 'eicon-number-field',
				'keywords'     => [ 'loop', 'numbers', 'pagination' ],
				'hide_from_panel' => true,
			],
			'aae-a-loop-number' => [
				'is_internal'  => true,
				'label'        => 'Loop Page Number',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\LoopGrid\Aaeaddon_A_Loop_Number',
				'icon'         => 'eicon-number-field',
				'keywords'     => [ 'loop', 'number', 'pagination' ],
				'hide_from_panel' => true,
			],
			'aae-a-loop-loadmore' => [
				'is_internal'  => true,
				'label'        => 'Loop Load More',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\LoopGrid\Aaeaddon_A_Loop_LoadMore',
				'icon'         => 'eicon-plus-circle',
				'keywords'     => [ 'loop', 'load more', 'pagination' ],
				'hide_from_panel' => true,
			],
			'aae-a-loop-arrow' => [
				'is_internal'  => true,
				'label'        => 'Loop Arrow',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\LoopGrid\Aaeaddon_A_Loop_Arrow',
				'icon'         => 'eicon-chevron-right',
				'keywords'     => [ 'loop', 'arrow', 'pagination' ],
				'hide_from_panel' => true,
			],
			'aae-a-loop-nav-wrap' => [
				'is_internal'  => true,
				'label'        => 'Loop Nav',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\LoopGrid\Aaeaddon_A_Loop_Nav_Wrap',
				'icon'         => 'eicon-navigation-horizontal',
				'keywords'     => [ 'loop', 'nav', 'pagination' ],
				'hide_from_panel' => true,
			],

			'aae-a-search-form' => [
				'label'        => 'Search Form',
				'description'  => 'Composite Ajax search form (inline / dropdown / fullscreen) with category & date filters — every part is a styleable atomic element.',
				'icon'         => 'eicon-search',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\SearchForm\Aaeaddon_A_Search_Form',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [ 'search', 'form', 'ajax', 'filter', 'atomic', 'composite' ],
				'category'     => 'form',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],
			'aae-a-search-toggle' => [
				'is_internal'  => true,
				'label'        => 'Search Toggle',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\SearchForm\Aaeaddon_A_Search_Toggle',
				'icon'         => 'eicon-search',
				'keywords'     => [ 'search', 'toggle' ],
				'hide_from_panel' => true,
			],
			'aae-a-search-toggle-open' => [
				'is_internal'  => true,
				'label'        => 'Open Icon',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\SearchForm\Aaeaddon_A_Search_Toggle_Open',
				'icon'         => 'eicon-search',
				'keywords'     => [ 'search', 'toggle', 'icon' ],
				'hide_from_panel' => true,
			],
			'aae-a-search-toggle-close' => [
				'is_internal'  => true,
				'label'        => 'Close Icon',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\SearchForm\Aaeaddon_A_Search_Toggle_Close',
				'icon'         => 'eicon-close',
				'keywords'     => [ 'search', 'toggle', 'icon', 'close' ],
				'hide_from_panel' => true,
			],
			'aae-a-search-panel' => [
				'is_internal'  => true,
				'label'        => 'Search Panel',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\SearchForm\Aaeaddon_A_Search_Panel',
				'icon'         => 'eicon-container',
				'keywords'     => [ 'search', 'panel' ],
				'hide_from_panel' => true,
			],
			'aae-a-search-field' => [
				'is_internal'  => true,
				'label'        => 'Search Field',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\SearchForm\Aaeaddon_A_Search_Field',
				'icon'         => 'eicon-form-horizontal',
				'keywords'     => [ 'search', 'field', 'form' ],
				'hide_from_panel' => true,
			],
			'aae-a-search-input' => [
				'is_internal'  => true,
				'label'        => 'Search Input',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\SearchForm\Aaeaddon_A_Search_Input',
				'icon'         => 'eicon-form-horizontal',
				'keywords'     => [ 'search', 'input' ],
				'hide_from_panel' => true,
			],
			'aae-a-search-filter-date' => [
				'is_internal'  => true,
				'label'        => 'Date Filter',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\SearchForm\Aaeaddon_A_Search_Filter_Date',
				'icon'         => 'eicon-calendar',
				'keywords'     => [ 'search', 'filter', 'date' ],
				'hide_from_panel' => true,
			],
			'aae-a-search-filter-category' => [
				'is_internal'  => true,
				'label'        => 'Category Filter',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\SearchForm\Aaeaddon_A_Search_Filter_Category',
				'icon'         => 'eicon-folder',
				'keywords'     => [ 'search', 'filter', 'category' ],
				'hide_from_panel' => true,
			],
			'aae-a-search-submit' => [
				'is_internal'  => true,
				'label'        => 'Search Submit',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\SearchForm\Aaeaddon_A_Search_Submit',
				'icon'         => 'eicon-button',
				'keywords'     => [ 'search', 'submit', 'button' ],
				'hide_from_panel' => true,
			],
			'aae-a-search-results' => [
				'is_internal'  => true,
				'label'        => 'Search Results',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\SearchForm\Aaeaddon_A_Search_Results',
				'icon'         => 'eicon-post-list',
				'keywords'     => [ 'search', 'results', 'ajax' ],
				'hide_from_panel' => true,
			],

			'aae-a-posts' => [
				'label'        => 'Posts Grid',
				'description'  => 'A dynamic grid of recent posts with GSAP stagger animations.',
				'icon'         => 'eicon-posts-grid',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => false,
				'keywords'     => [
					'posts',
					'grid',
					'blog',
					'atomic',
					'dynamic',
				],
				'category'     => 'dynamic',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-post-card' => [
				'is_internal'  => true,
				'label'        => 'Post Card (Internal)',
				'description'  => 'Internal child card for the Posts Grid widget.',
				'icon'         => 'eicon-post-list',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [ 'post card', 'internal' ],
				'category'     => 'general',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-loop-grid' => [
				'label'        => 'Loop Grid',
				'description'  => 'Query posts and repeat a custom loop-item template per post (built from atomic widgets).',
				'icon'         => 'eicon-loop-builder',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'loop',
					'grid',
					'posts',
					'query',
					'template',
					'dynamic',
				],
				'category'     => 'dynamic',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-loop-grid-slider' => [
				'label'        => 'Loop Grid Slider',
				'description'  => 'Query posts and present each as a slide, driven by the shared nested-slider runtime (effect / autoplay / coverflow / 3D) with AJAX load-more paging.',
				'icon'         => 'eicon-slider-push',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'loop',
					'grid',
					'slider',
					'carousel',
					'posts',
					'query',
					'dynamic',
				],
				'category'     => 'slider',
				'order'        => 1,
				'demo_url'     => '',
				'doc_url'      => '',
			],
			'aae-a-loop-slide-track' => [
				'is_internal'  => true,
				'label'        => 'Slider Track',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\LoopGridSlider\Aaeaddon_A_Loop_Slide_Track',
				'icon'         => 'eicon-slider-push',
				'keywords'     => [ 'loop', 'slider', 'track' ],
				'hide_from_panel' => true,
			],
			'aae-a-loop-slide-item' => [
				'is_internal'  => true,
				'label'        => 'Loop Slide Item',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\LoopGridSlider\Aaeaddon_A_Loop_Slide_Item',
				'icon'         => 'eicon-container',
				'keywords'     => [ 'loop', 'slide', 'item' ],
				'hide_from_panel' => true,
			],
			'aae-a-loop-slide-pagination' => [
				'is_internal'  => true,
				'label'        => 'Slider Pagination',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\LoopGridSlider\Aaeaddon_A_Loop_Slide_Pagination',
				'icon'         => 'eicon-ellipsis-h',
				'keywords'     => [ 'loop', 'slider', 'pagination' ],
				'hide_from_panel' => true,
			],

			'aae-a-post-pagination' => [
				'label'        => 'Post Pagination',
				'description'  => 'Prev/Next single-post navigation — taxonomy-constrained, orderable (date/title/menu-order/custom-field), loop-around, sticky-bar/side-arrow display modes, keyboard/swipe/prefetch, and a customizable Hover Preview Card. Works on WooCommerce single Product pages too.',
				'icon'         => 'eicon-post-navigation',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'post',
					'nav',
					'navigation',
					'prev',
					'next',
					'pagination',
					'dynamic',
				],
				'category'     => 'blog',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-post-pagination-prev' => [
				'is_internal'  => true,
				'label'        => 'Previous Post',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\PostPagination\Aaeaddon_A_Post_Pagination_Prev',
				'icon'         => 'eicon-chevron-left',
				'keywords'     => [ 'post', 'nav', 'prev' ],
				'hide_from_panel' => true,
			],

			'aae-a-post-pagination-next' => [
				'is_internal'  => true,
				'label'        => 'Next Post',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\PostPagination\Aaeaddon_A_Post_Pagination_Next',
				'icon'         => 'eicon-chevron-right',
				'keywords'     => [ 'post', 'nav', 'next' ],
				'hide_from_panel' => true,
			],

			'aae-a-post-pagination-preview' => [
				'is_internal'  => true,
				'label'        => 'Hover Preview Card',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\PostPagination\Aaeaddon_A_Post_Pagination_Preview',
				'icon'         => 'eicon-post-navigation',
				'keywords'     => [ 'post', 'preview', 'hover', 'card' ],
				'hide_from_panel' => true,
			],

			'aae-a-post-pagination-preview-image' => [
				'is_internal'  => true,
				'label'        => 'Thumbnail',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\PostPagination\Aaeaddon_A_Post_Pagination_Preview_Image',
				'icon'         => 'eicon-image',
				'keywords'     => [ 'post', 'pagination', 'preview', 'thumbnail', 'image' ],
				'hide_from_panel' => true,
			],

			'aae-a-post-pagination-preview-category' => [
				'is_internal'  => true,
				'label'        => 'Category',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\PostPagination\Aaeaddon_A_Post_Pagination_Preview_Category',
				'icon'         => 'eicon-tags',
				'keywords'     => [ 'post', 'pagination', 'preview', 'category' ],
				'hide_from_panel' => true,
			],

			'aae-a-post-pagination-preview-title' => [
				'is_internal'  => true,
				'label'        => 'Title',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\PostPagination\Aaeaddon_A_Post_Pagination_Preview_Title',
				'icon'         => 'eicon-t-letter',
				'keywords'     => [ 'post', 'pagination', 'preview', 'title' ],
				'hide_from_panel' => true,
			],

			'aae-a-post-pagination-preview-date' => [
				'is_internal'  => true,
				'label'        => 'Date',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\PostPagination\Aaeaddon_A_Post_Pagination_Preview_Date',
				'icon'         => 'eicon-calendar',
				'keywords'     => [ 'post', 'pagination', 'preview', 'date' ],
				'hide_from_panel' => true,
			],

			'aae-a-post-pagination-preview-author' => [
				'is_internal'  => true,
				'label'        => 'Author',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\PostPagination\Aaeaddon_A_Post_Pagination_Preview_Author',
				'icon'         => 'eicon-user-circle-o',
				'keywords'     => [ 'post', 'pagination', 'preview', 'author' ],
				'hide_from_panel' => true,
			],

			'aae-a-post-pagination-preview-excerpt' => [
				'is_internal'  => true,
				'label'        => 'Excerpt',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\PostPagination\Aaeaddon_A_Post_Pagination_Preview_Excerpt',
				'icon'         => 'eicon-text-align-left',
				'keywords'     => [ 'post', 'pagination', 'preview', 'excerpt' ],
				'hide_from_panel' => true,
			],

			/*
			 * AAE Post Comments family — DISABLED 2026-07-27: the senior dev
			 * is building the comments/reply-form feature himself. Kept here
			 * (not deleted) for reference; root class renamed to
			 * AAE_A_Comments_Ny / e-aae-a-comments-ny so it can't collide
			 * with whatever he ends up calling his own version. Uncomment
			 * this whole block (and the matching block in
			 * get_available_widgets(), and the internal-widgets list in
			 * is_widget_active()) to re-enable.
			 *
			'aae-a-comments-ny' => [
				'label'        => 'Post Comments',
				'description'  => 'Query the current post\'s comments and repeat a custom comment-item template per comment (avatar/author/date/content/reply-link, freely mixed with Paragraph/Image/Button/Heading), plus a native reply form.',
				'icon'         => 'eicon-comments',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'comment',
					'comments',
					'discussion',
					'reply',
					'template',
					'dynamic',
				],
				'category'     => 'blog',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-comment-list' => [
				'is_internal'  => true,
				'label'        => 'Comment List',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\Comments\AAE_A_Comment_List',
				'icon'         => 'eicon-comments',
				'keywords'     => [ 'comment', 'list' ],
				'hide_from_panel' => true,
			],

			'aae-a-comment-item' => [
				'is_internal'  => true,
				'label'        => 'Comment Item',
				'description'  => 'Container widget for Post Comments items with default flex column layout.',
				'icon'         => 'eicon-container',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\Comments\AAE_A_Comment_Item',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'comment',
					'item',
					'container',
					'flex',
					'column',
					'atomic',
				],
				'category'     => 'general',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
				'default_children' => [],
			],

			'aae-a-comment-avatar' => [
				'label'        => 'AAE Comment Avatar',
				'description'  => 'The current comment\'s avatar — resolves per comment inside a Post Comments item.',
				'icon'         => 'eicon-person',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [ 'comment', 'avatar', 'gravatar', 'atomic', 'dynamic' ],
				'category'     => 'blog',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-comment-author' => [
				'label'        => 'AAE Comment Author',
				'description'  => 'The current comment\'s author name — resolves per comment inside a Post Comments item.',
				'icon'         => 'eicon-t-letter',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [ 'comment', 'author', 'name', 'atomic', 'dynamic' ],
				'category'     => 'blog',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-comment-date' => [
				'label'        => 'AAE Comment Date',
				'description'  => 'The current comment\'s date/time — resolves per comment inside a Post Comments item.',
				'icon'         => 'eicon-calendar',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [ 'comment', 'date', 'time', 'atomic', 'dynamic' ],
				'category'     => 'blog',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-comment-content' => [
				'label'        => 'AAE Comment Content',
				'description'  => 'The current comment\'s text — resolves per comment inside a Post Comments item.',
				'icon'         => 'eicon-text-align-left',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [ 'comment', 'content', 'text', 'atomic', 'dynamic' ],
				'category'     => 'blog',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-comment-reply-link' => [
				'label'        => 'AAE Comment Reply Link',
				'description'  => 'The current comment\'s reply link — resolves per comment inside a Post Comments item.',
				'icon'         => 'eicon-reply',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [ 'comment', 'reply', 'link', 'atomic', 'dynamic' ],
				'category'     => 'blog',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-comment-form' => [
				'label'        => 'AAE Comment Form',
				'description'  => 'A restyleable wrapper around WordPress\'s native comment_form() — real submissions, nonces and comment-reply threading included.',
				'icon'         => 'eicon-form-horizontal',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [ 'comment', 'form', 'reply', 'submit', 'atomic', 'dynamic' ],
				'category'     => 'blog',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],
			*/

			'aae-a-counter' => [
				'label'        => 'Counter',
				'description'  => 'An animated number counter that counts up on scroll, with a minimal CSS footprint.',
				'icon'         => 'eicon-counter',
				'is_pro'       => true,
				'badge_only'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'counter',
					'number',
					'atomic',
					'gsap',
					'animate',
				],
				'category'     => 'general',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-advanced-heading' => [
				'label'        => 'Advanced Heading',
				'description'  => 'Heading with rich inline text editing — bold, italic, underline, strikethrough, super/subscript and links, on any tag from h1 to span.',
				'icon'         => 'eicon-t-letter',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'heading',
					'title',
					'highlight',
					'html',
					'span',
					'atomic',
				],
				'category'     => 'general',
				'order'        => 0,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-slider' => [
				'label'        => 'Nested Slider',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slider',
				'keywords'     => ['atomic', 'slider', 'carousel'],
				'icon'         => 'eicon-slider-push',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'category'     => 'slider',
				'order'        => 1,
				'demo_url'     => '',
				'doc_url'      => '',
			],
			'aae-a-slide' => [
				'is_internal'  => true,
				'label'        => 'Slide (Internal)',
				'description'  => 'Internal child container for Nested Slider.',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slide',
				'keywords'     => ['atomic', 'slide', 'internal'],
				'icon'         => 'eicon-slide',
				'hide_from_panel' => true,
			],
			'aae-a-slider-track' => [
				'is_internal'  => true,
				'label'        => 'Slider Track',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slider_Track',
				'keywords'     => ['atomic', 'slider', 'track'],
				'icon'         => 'eicon-slider-push',
				'hide_from_panel' => true,
			],
			'aae-a-slider-nav-prev' => [
				'is_internal'  => true,
				'label'        => 'Slider Prev Nav',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slider_Nav_Prev',
				'keywords'     => ['atomic', 'slider', 'navigator', 'prev'],
				'icon'         => 'eicon-chevron-left',
				'hide_from_panel' => true,
			],
			'aae-a-slider-nav-next' => [
				'is_internal'  => true,
				'label'        => 'Slider Next Nav',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slider_Nav_Next',
				'keywords'     => ['atomic', 'slider', 'navigator', 'next'],
				'icon'         => 'eicon-chevron-right',
				'hide_from_panel' => true,
			],
			'aae-a-slider-pagination' => [
				'is_internal'  => true,
				'label'        => 'Slider Pagination',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slider_Pagination',
				'keywords'     => ['atomic', 'slider', 'pagination', 'dots'],
				'icon'         => 'eicon-ellipsis-h',
				'hide_from_panel' => true,
			],

			// ── Nested Slider — remaining HELPER widgets. These were registered
			// as classes and routed through WIDGET_PARENT_MAP, but had no entry
			// here at all, so nothing could name them. `is_internal => true`
			// keeps them out of the dashboard list exactly like their siblings
			// above; the label/icon exist so the parent can list what it owns.
			'aae-a-slider-dot' => [
				'is_internal'  => true,
				'label'        => 'Slider Dot',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slider_Dot',
				'keywords'     => ['atomic', 'slider', 'dot', 'bullet'],
				'icon'         => 'eicon-dot-circle-o',
				'hide_from_panel' => true,
			],

			'aae-a-slider-indicators' => [
				'is_internal'  => true,
				'label'        => 'Slider Indicators',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slider_Indicators',
				'keywords'     => ['atomic', 'slider', 'indicators'],
				'icon'         => 'eicon-ellipsis-h',
				'hide_from_panel' => true,
			],

			'aae-a-slider-current' => [
				'is_internal'  => true,
				'label'        => 'Slider Current Index',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slider_Current',
				'keywords'     => ['atomic', 'slider', 'current', 'index'],
				'icon'         => 'eicon-number-field',
				'hide_from_panel' => true,
			],

			'aae-a-slider-total' => [
				'is_internal'  => true,
				'label'        => 'Slider Total',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slider_Total',
				'keywords'     => ['atomic', 'slider', 'total', 'count'],
				'icon'         => 'eicon-number-field',
				'hide_from_panel' => true,
			],

			'aae-a-slider-percentage' => [
				'is_internal'  => true,
				'label'        => 'Slider Percentage',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slider_Percentage',
				'keywords'     => ['atomic', 'slider', 'percentage', 'progress'],
				'icon'         => 'eicon-number-field',
				'hide_from_panel' => true,
			],

			'aae-a-slider-progress' => [
				'is_internal'  => true,
				'label'        => 'Slider Progress',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slider_Progress',
				'keywords'     => ['atomic', 'slider', 'progress', 'bar'],
				'icon'         => 'eicon-skill-bar',
				'hide_from_panel' => true,
			],

			'aae-a-slider-progress-fill' => [
				'is_internal'  => true,
				'label'        => 'Slider Progress Fill',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slider_Progress_Fill',
				'keywords'     => ['atomic', 'slider', 'progress', 'fill'],
				'icon'         => 'eicon-skill-bar',
				'hide_from_panel' => true,
			],

			'aae-a-slider-counter' => [
				'is_internal'  => true,
				'label'        => 'Slider Counter',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slider_Counter',
				'keywords'     => ['atomic', 'slider', 'counter'],
				'icon'         => 'eicon-counter',
				'hide_from_panel' => true,
			],

			'aae-a-slider-divider' => [
				'is_internal'  => true,
				'label'        => 'Slider Divider',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\NestedSlider\Aaeaddon_A_Slider_Divider',
				'keywords'     => ['atomic', 'slider', 'divider', 'separator'],
				'icon'         => 'eicon-divider',
				'hide_from_panel' => true,
			],

			'aae-a-accordion' => [
				'label'        => 'Accordion',
				'description'  => 'Atomic accordion with GSAP interactive effects and smooth controls.',
				'icon'         => 'eicon-accordion',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'accordion',
					'tabs',
					'toggle',
					'atomic',
					'gsap',
				],
				'category'     => 'general',
				'order'        => 6,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-accordion-item' => [
				'is_internal'  => true,
				'label'        => 'Accordion Item',
				'description'  => 'Internal child container for Accordion.',
				'icon'         => 'eicon-accordion',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'accordion item',
					'internal',
				],
				'category'     => 'general',
				'order'        => 7,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-icon-list' => [
				'label'        => 'Icon List',
				'description'  => 'An atomic icon list widget with custom icons, text, and link support.',
				'icon'         => 'eicon-bullet-list',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'list',
					'icon',
					'bullet',
					'atomic',
					'item',
				],
				'category'     => 'general',
				'order'        => 8,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-icon-list-item' => [
				'is_internal'  => true,
				'label'        => 'Icon List Item',
				'description'  => 'Internal child item for Icon List.',
				'icon'         => 'eicon-bullet-list',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'list item',
					'internal',
				],
				'category'     => 'general',
				'order'        => 9,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			// ── Social Share — PARENT widget. This is the only Social Share
			// entry exposed in the dashboard widget list / editor panel.
			'aae-a-social-share' => [
				'label'        => 'Social Share',
				'description'  => 'An open, unlocked social-share row — three editable icon+label items to duplicate, restyle, or delete. Pair with the ready-made minimal/outlined/solid templates.',
				'icon'         => 'eicon-share',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'social',
					'share',
					'atomic',
					'aae',
					'open',
				],
				'category'     => 'general',
				'order'        => 10,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			// ── Social Share — HELPER widget below. `is_internal => true`
			// hides it from the dashboard widget list; it is never
			// individually toggled, only used internally by Social Share
			// above (managed via its "Items" repeater control).
			'aae-a-social-share-item' => [
				'is_internal'  => true,
				'label'        => 'Social Share Item',
				'description'  => 'Internal child item for Social Share.',
				'icon'         => 'eicon-share',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'social',
					'share',
					'item',
					'link',
				],
				'category'     => 'general',
				'order'        => 11,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-social-share-item-icon' => [
				'is_internal'  => true,
				'label'        => 'Social Share Item — Icon',
				'description'  => 'Internal icon sub-element used by the Social Share Item.',
				'icon'         => 'eicon-svg',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [ 'social', 'share', 'icon', 'atomic' ],
				'category'     => 'general',
				'order'        => 12,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-social-share-item-title' => [
				'is_internal'  => true,
				'label'        => 'Social Share Item — Title',
				'description'  => 'Internal title sub-element used by the Social Share Item.',
				'icon'         => 'eicon-t-letter-bold',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [ 'social', 'share', 'title', 'atomic' ],
				'category'     => 'general',
				'order'        => 12,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			// 'aae-a-social-share-main' / '-main-item' removed: the whole
			// Widgets/SocialShareMain/ directory was deleted in 165a85e5, but
			// these entries were left behind. Class loading is file_exists()
			// guarded so they failed silently, while the script enqueue was
			// not — the editor 404'd on assets/atomic/js/social-share-main.js
			// on every load. Use 'aae-a-social-share' instead.

			'aae-a-image-compare' => [
				'label'        => 'Image Compare',
				'description'  => 'A draggable before/after image comparison slider — no manual setup needed, apply the ready-made Horizontal/Vertical presets and swap in your own images.',
				'icon'         => 'eicon-image-before-after',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'image',
					'compare',
					'before',
					'after',
					'slider',
					'atomic',
					'template',
				],
				'category'     => 'general',
				'order'        => 9,
				'demo_url'     => '',
				'doc_url'      => '',
			],


			'aae-a-countdown' => [
				'label'        => 'Countdown',
				'description'  => 'A composite countdown timer with four locked time units (days, hours, minutes, seconds) — each unit, digit, and label is an independent atomic child styleable from its own Style panel.',
				'icon'         => 'eicon-countdown',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'countdown',
					'timer',
					'date',
					'expire',
					'atomic',
					'composite',
				],
				'category'     => 'general',
				'order'        => 11,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-countdown-unit' => [
				'is_internal'  => true,
				'label'        => 'Countdown — Unit',
				'description'  => 'Internal time-fragment sub-element used by Countdown (days, hours, minutes, seconds).',
				'icon'         => 'eicon-clock-o',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'countdown',
					'unit',
					'atomic',
				],
				'category'     => 'general',
				'order'        => 12,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			// ── Timeline — PARENT widget. This is the only Timeline entry
			// exposed in the dashboard widget list / editor panel.
			'aae-a-timeline' => [
				'label'        => 'Timeline',
				'description'  => 'A composite vertical timeline with four locked event items — each marker, date, title, and description is an independent atomic child styleable from its own Style panel.',
				'icon'         => 'eicon-time-line',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'timeline',
					'history',
					'roadmap',
					'atomic',
					'composite',
				],
				'category'     => 'general',
				'order'        => 13,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			// ── Timeline — HELPER widgets below. `is_internal => true` hides
			// each of these from the dashboard widget list; they are never
			// individually toggled, only used internally by Timeline above.
			'aae-a-timeline-item' => [
				'label'        => 'Timeline — Item',
				'description'  => 'Internal event-row sub-element used by Timeline (marker + date + title + description).',
				'icon'         => 'eicon-bullet-list',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [
					'timeline',
					'item',
					'event',
					'atomic',
				],
				'category'     => 'general',
				'order'        => 14,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-timeline-number' => [
				'label'        => 'Timeline — Number',
				'description'  => 'Internal milestone-index label used by Timeline — Item.',
				'icon'         => 'eicon-number-field',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'timeline', 'number', 'atomic' ],
				'category'     => 'general',
				'order'        => 15,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-timeline-year' => [
				'label'        => 'Timeline — Year',
				'description'  => 'Internal milestone-date label used by Timeline — Item.',
				'icon'         => 'eicon-calendar',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'timeline', 'year', 'date', 'atomic' ],
				'category'     => 'general',
				'order'        => 16,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-timeline-title' => [
				'label'        => 'Timeline — Title',
				'description'  => 'Internal milestone-title label used by Timeline — Item.',
				'icon'         => 'eicon-t-letter-bold',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'timeline', 'title', 'heading', 'atomic' ],
				'category'     => 'general',
				'order'        => 17,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-timeline-desc' => [
				'label'        => 'Timeline — Description',
				'description'  => 'Internal milestone-description paragraph used by Timeline — Item.',
				'icon'         => 'eicon-paragraph',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'timeline', 'description', 'paragraph', 'atomic' ],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			// ── Progress Bar Template — PARENT widget #1. The only entry of
			// this sub-group exposed in the dashboard widget list.
			'aae-a-progressbar' => [
				'label'        => 'Progress Bar',
				'description'  => 'An open progress-bar container — drops as a plain Line bar built from real track/fill/label children you can restyle natively, with Circle and Dot presets one click away.',
				'icon'         => 'eicon-skill-bar',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'progress',
					'progressbar',
					'bar',
					'template',
					'container',
					'atomic',
				],
				'category'     => 'general',
				'order'        => 12,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			// ── Progress Bar Template — HELPER widgets below. `is_internal
			// => true` hides these from the dashboard widget list; they are
			// only used internally by "Progress Bar Template" above.
			'aae-a-progressbar-track' => [
				'label'        => 'Progress Bar — Track',
				'description'  => 'Internal track sub-element used by the Progress Bar Template.',
				'icon'         => 'eicon-skill-bar',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'progress', 'progressbar', 'track', 'atomic' ],
				'category'     => 'general',
				'order'        => 12,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-progressbar-fill' => [
				'label'        => 'Progress Bar — Fill',
				'description'  => 'Internal fill sub-element used by the Progress Bar Template\'s Track.',
				'icon'         => 'eicon-skill-bar',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'progress', 'progressbar', 'fill', 'atomic' ],
				'category'     => 'general',
				'order'        => 12,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-progressbar-label' => [
				'label'        => 'Progress Bar — Label',
				'description'  => 'Internal percentage-label sub-element used by the Progress Bar Template.',
				'icon'         => 'eicon-t-letter-bold',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'progress', 'progressbar', 'label', 'atomic' ],
				'category'     => 'general',
				'order'        => 12,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-progressbar-dot' => [
				'label'        => 'Progress Bar — Dot',
				'description'  => 'Internal step-dot sub-element used by the Progress Bar Template\'s Dot preset.',
				'icon'         => 'eicon-dot-circle-o',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'progress', 'progressbar', 'dot', 'atomic' ],
				'category'     => 'general',
				'order'        => 12,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			// ── Toggle Switcher — PARENT widget #1. The only entry of this
			// sub-group exposed in the dashboard widget list.
			'aae-a-toggle-switcher' => [
				'label'        => 'Toggle Switcher',
				'description'  => 'A dual-panel content toggle with two styles — classic switch or label highlight.',
				'icon'         => 'eicon-t-letter',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'toggle',
					'switch',
					'tabs',
					'atomic',
					'switcher',
				],
				'category'     => 'general',
				'order'        => 13,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			// ── Toggle Switcher — HELPER widgets below. `is_internal =>
			// true` hides these from the dashboard widget list; they are
			// only used internally by "Toggle Switcher" above.
			'aae-a-toggle-pane' => [
				'label'        => 'Toggle Pane (Internal)',
				'description'  => 'Internal child container for Toggle Switcher.',
				'icon'         => 'eicon-inner-section',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [
					'toggle pane',
					'internal',
				],
				'category'     => 'general',
				'order'        => 14,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-toggle-switcher-tabs' => [
				'label'        => 'Toggle Switcher — Tabs',
				'description'  => 'Internal tabs row used by the Toggle Switcher.',
				'icon'         => 'eicon-t-letter',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'toggle', 'switch', 'tabs', 'atomic' ],
				'category'     => 'general',
				'order'        => 14,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-toggle-switcher-tab' => [
				'label'        => 'Toggle Switcher — Tab',
				'description'  => 'Internal tab button used by the Toggle Switcher Tabs row.',
				'icon'         => 'eicon-t-letter',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'toggle', 'switch', 'tab', 'atomic' ],
				'category'     => 'general',
				'order'        => 14,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-toggle-pane-title' => [
				'label'        => 'Toggle Pane — Title',
				'description'  => 'Internal pane-title label used by the Toggle Pane.',
				'icon'         => 'eicon-t-letter-bold',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'toggle', 'pane', 'title', 'atomic' ],
				'category'     => 'general',
				'order'        => 14,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-toggle-pane-desc' => [
				'label'        => 'Toggle Pane — Description',
				'description'  => 'Internal pane-description paragraph used by the Toggle Pane.',
				'icon'         => 'eicon-paragraph',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'toggle', 'pane', 'description', 'atomic' ],
				'category'     => 'general',
				'order'        => 14,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-toggle-switcher-label' => [
				'label'        => 'Toggle Switcher — Label',
				'description'  => 'Internal before/after label used by the Switch-style Toggle Switcher preset.',
				'icon'         => 'eicon-t-letter',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'toggle', 'switch', 'label', 'atomic' ],
				'category'     => 'general',
				'order'        => 14,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-toggle-switcher-tablist' => [
				'label'        => 'Toggle Switcher — Tablist',
				'description'  => 'Internal role="tablist" wrapper for the Track + Labels used by the Switch-style Toggle Switcher preset.',
				'icon'         => 'eicon-t-letter',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'toggle', 'switch', 'tablist', 'atomic' ],
				'category'     => 'general',
				'order'        => 14,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-toggle-switcher-track' => [
				'label'        => 'Toggle Switcher — Track',
				'description'  => 'Internal knob track used by the Switch-style Toggle Switcher preset.',
				'icon'         => 'eicon-toggle',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'toggle', 'switch', 'track', 'knob', 'atomic' ],
				'category'     => 'general',
				'order'        => 14,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-toggle-switcher-knob' => [
				'label'        => 'Toggle Switcher — Knob',
				'description'  => 'Internal knob dot used by the Switch-style Toggle Switcher preset.',
				'icon'         => 'eicon-dot-circle-o',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'toggle', 'switch', 'knob', 'atomic' ],
				'category'     => 'general',
				'order'        => 14,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form' => [
				'label'        => 'Form',
				'description'  => 'Atomic-first form: real child fields, locked submit button. Milestone 1 skeleton — no submit logic yet.',
				'icon'         => 'eicon-form-horizontal',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form',
					'contact',
					'lead',
					'atomic',
				],
				'category'     => 'form',
				'order'        => 17,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-label' => [
				'is_internal'  => true,
				'label'        => 'Form Label',
				'description'  => 'Label widget for AAE Form — linked to an input by ID; drag from the panel to add more fields.',
				'icon'         => 'eicon-t-letter',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form label',
					'internal',
				],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-input' => [
				'is_internal'  => true,
				'label'        => 'Form Input',
				'description'  => 'Input widget for AAE Form — text/email/number/tel/password via a type prop.',
				'icon'         => 'eicon-form-horizontal',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form input',
					'internal',
				],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-textarea' => [
				'is_internal'  => true,
				'label'        => 'Form Textarea',
				'description'  => 'Textarea widget for AAE Form.',
				'icon'         => 'eicon-textarea',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form textarea',
					'internal',
				],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-checkbox' => [
				'is_internal'  => true,
				'label'        => 'Form Checkbox',
				'description'  => 'Checkbox widget for AAE Form — fully styleable, with checked state.',
				'icon'         => 'eicon-check-circle',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form checkbox',
				],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-radio' => [
				'is_internal'  => true,
				'label'        => 'Form Radio',
				'description'  => 'Radio button widget for AAE Form — radios sharing a group name are exclusive.',
				'icon'         => 'eicon-circle-o',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form radio',
				],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-select' => [
				'is_internal'  => true,
				'label'        => 'Form Select',
				'description'  => 'Select/dropdown widget for AAE Form — options one per line, value|Label.',
				'icon'         => 'eicon-select',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form select',
					'dropdown',
				],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-success-message' => [
				'is_internal'  => true,
				'label'        => 'Form Success Message (Internal)',
				'description'  => 'Locked status container shown when the form submits successfully.',
				'icon'         => 'eicon-check',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form success',
					'internal',
				],
				'category'     => 'general',
				'order'        => 19,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-error-message' => [
				'is_internal'  => true,
				'label'        => 'Form Error Message (Internal)',
				'description'  => 'Locked status container shown when the form submission fails.',
				'icon'         => 'eicon-close',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form error',
					'internal',
				],
				'category'     => 'general',
				'order'        => 19,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-file' => [
				'is_internal'  => true,
				'label'        => 'Form File Upload',
				'description'  => 'File upload field for AAE Form — files land in private local storage, validated server-side (type, size), downloadable only by admins.',
				'icon'         => 'eicon-upload',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form file',
					'upload',
					'attachment',
				],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-field-error' => [
				'is_internal'  => true,
				'label'        => 'Form Field Error',
				'description'  => 'Style source for inline validation messages — its look and text are copied onto every "This field is required." error the form shows. Deleting it never removes validation; errors just fall back to the default look.',
				'icon'         => 'eicon-warning',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form error',
					'validation',
					'required',
				],
				'category'     => 'general',
				'order'        => 19,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-rating' => [
				'is_internal'  => true,
				'label'        => 'Form Rating',
				'description'  => 'Advanced Field (Pro) — a star-rating field. Progressively enhances a real number input, so submit and validation work exactly like any other number field.',
				'icon'         => 'eicon-star-o',
				'is_pro'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form rating',
					'star',
					'review',
					'feedback',
				],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-range' => [
				'is_internal'  => true,
				'label'        => 'Form Range',
				'description'  => 'Advanced Field (Pro) — a range slider. Style tab → Background Color sets the slider\'s own color.',
				'icon'         => 'eicon-slider-push',
				'is_pro'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form range',
					'slider',
					'range',
				],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-range-group' => [
				'is_internal'  => true,
				'label'        => 'Form Range Group',
				'description'  => 'A labelled slider row — heading, live value readout and slider, each a real child you select and style on its own. The slider is the Range field, so it submits and validates like one.',
				'icon'         => 'eicon-slider-push',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form range group',
					'slider',
					'range',
					'label',
					'value',
				],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-range-value' => [
				'is_internal'  => true,
				'label'        => 'Form Range Value',
				'description'  => 'The live value readout inside a Range Group — prints the slider\'s current value with an optional prefix/suffix.',
				'icon'         => 'eicon-number-field',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form range value',
					'readout',
					'output',
					'internal',
				],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-password' => [
				'is_internal'  => true,
				'label'        => 'Form Password',
				'description'  => 'Advanced Field (Pro) — a masked password field with an optional reveal button, minimum length and confirm-match. Never stored, emailed or sent to webhooks in readable form.',
				'icon'         => 'eicon-lock-user',
				'is_pro'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form password',
					'password',
					'secret',
					'confirm',
				],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-calculation' => [
				'is_internal'  => true,
				'label'        => 'Form Calculation',
				'description'  => 'Advanced Field (Pro) — a read-only total computed from other fields by a formula, e.g. {quantity} * {price}. The server recomputes it on submit, so the stored value can never be tampered with.',
				'icon'         => 'eicon-number-field',
				'is_pro'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form calculation',
					'calculator',
					'total',
					'price',
					'quote',
					'sum',
				],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-country' => [
				'is_internal'  => true,
				'label'        => 'Form Country',
				'description'  => 'Advanced Field (Pro) — a country dropdown with the full ISO country list built in. Prune or reorder the list to pin priority countries; values submit as ISO codes.',
				'icon'         => 'eicon-globe',
				'is_pro'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form country',
					'country',
					'dropdown',
					'nationality',
				],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-submit' => [
				'is_internal'  => true,
				'label'        => 'Form Submit Button',
				'description'  => 'Submit button widget for AAE Form — drag from the panel to place it anywhere inside the form.',
				'icon'         => 'eicon-button',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form submit',
					'internal',
				],
				'category'     => 'general',
				'order'        => 19,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-step' => [
				'is_internal'  => true,
				'label'        => 'Form Step',
				'description'  => 'Multi-Step Forms (Pro) — one page of a multi-step form. Add 2+ inside a form to turn it into a wizard with Next/Previous navigation and per-step validation.',
				'icon'         => 'eicon-single-page',
				'is_pro'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form step',
					'multi-step',
					'wizard',
					'page',
				],
				'category'     => 'general',
				'order'        => 19,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-next' => [
				'is_internal'  => true,
				'label'        => 'Next Step Button',
				'description'  => 'Multi-Step Forms (Pro) — advances a multi-step form to the next step. Validates the current step first.',
				'icon'         => 'eicon-arrow-right',
				'is_pro'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form next',
					'multi-step',
					'wizard',
					'button',
				],
				'category'     => 'general',
				'order'        => 19,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-form-prev' => [
				'is_internal'  => true,
				'label'        => 'Previous Step Button',
				'description'  => 'Multi-Step Forms (Pro) — steps a multi-step form back one step. Never validated.',
				'icon'         => 'eicon-arrow-left',
				'is_pro'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'form previous',
					'form back',
					'multi-step',
					'wizard',
					'button',
				],
				'category'     => 'general',
				'order'        => 19,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-nav' => [
				'label'        => 'Nav',
				'description'  => 'Atomic navbar with fully styleable items and dropdown support.',
				'icon'         => 'eicon-nav-menu',
				'is_pro'       => true,
				'badge_only'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [ 'nav', 'menu', 'navbar', 'navigation', 'atomic', 'aae' ],
				'category'     => 'header-footer',
				'order'        => 17,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-nav-item' => [
				'is_internal'  => true,
				'label'        => 'Nav Item (Internal)',
				'description'  => 'Internal child item for Nav.',
				'icon'         => 'eicon-nav-menu',
				'is_pro'       => true,
				'badge_only'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [ 'nav item', 'internal' ],
				'category'     => 'header-footer',
				'order'        => 17,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			// ── Nav — remaining HELPER widgets. Registered as classes and
			// routed through WIDGET_PARENT_MAP, but with no entry here, so
			// nothing could name them (same gap as the slider parts above).
			'aae-a-nav-sub-item' => [
				'is_internal'  => true,
				'label'        => 'Nav Sub Item',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\Nav\Aaeaddon_A_Nav_Sub_Item',
				'keywords'     => [ 'nav', 'submenu', 'dropdown', 'internal' ],
				'icon'         => 'eicon-nav-menu',
				'hide_from_panel' => true,
			],

			'aae-a-mobile-nav' => [
				'is_internal'  => true,
				'label'        => 'Mobile Nav',
				'class_name'   => 'Wealcoder\AnimationAddons\AtomicWidgets\Widgets\Nav\Aaeaddon_A_Mobile_Nav',
				'keywords'     => [ 'nav', 'mobile', 'responsive', 'internal' ],
				'icon'         => 'eicon-menu-bar',
				'hide_from_panel' => true,
			],

			'aae-a-flip-box' => [
				'label'        => 'Flip Box',
				'description'  => 'An open, unlocked flip card — front and back faces are plain containers you can restyle or fill freely. Pair with the ready-made preset designs for each flip direction.',
				'icon'         => 'eicon-flip-box',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'flip',
					'box',
					'card',
					'hover',
					'atomic',
					'preset',
					'template',
				],
				'category'     => 'interaction',
				'order'        => 14,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-flip-box-front' => [
				'label'        => 'Flip Box Front (Internal)',
				'description'  => 'Internal front face container for the AAE Flip Box.',
				'icon'         => 'eicon-inner-section',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'flip face', 'internal' ],
				'category'     => 'general',
				'order'        => 17,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-flip-box-back' => [
				'label'        => 'Flip Box Back (Internal)',
				'description'  => 'Internal back face container for the AAE Flip Box.',
				'icon'         => 'eicon-inner-section',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'flip face', 'internal' ],
				'category'     => 'general',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-image-hotspot' => [
				'label'        => 'AAE Image Hotspot',
				'description'  => 'Interactive markers over an image — inline tooltips, teleported lightboxes (with drill-down support), a guided auto-tour, auto-numbered badges, and 6 marker animations.',
				'icon'         => 'eicon-image-hotspot',
				'is_pro'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'hotspot',
					'image',
					'tooltip',
					'lightbox',
					'tour',
					'marker',
					'atomic',
				],
				'category'     => 'interaction',
				'order'        => 20,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-hotspot-point' => [
				'label'        => 'Hotspot Point (Internal)',
				'description'  => 'Internal repeating marker for the AAE Image Hotspot. Inserted only via its Hotspots control.',
				'icon'         => 'eicon-point',
				'is_pro'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'hotspot point', 'internal' ],
				'category'     => 'general',
				'order'        => 21,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-hotspot-marker' => [
				'label'        => 'Hotspot Marker (Internal)',
				'description'  => 'Internal marker (icon/dot/text) for the AAE Hotspot Point.',
				'icon'         => 'eicon-point',
				'is_pro'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'hotspot marker', 'internal' ],
				'category'     => 'general',
				'order'        => 22,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-hotspot-content' => [
				'label'        => 'Hotspot Content (Internal)',
				'description'  => 'Internal tooltip/lightbox box for the AAE Hotspot Point.',
				'icon'         => 'eicon-post-content',
				'is_pro'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'hotspot content', 'internal' ],
				'category'     => 'general',
				'order'        => 23,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-hotspot-close' => [
				'label'        => 'Hotspot Close (Internal)',
				'description'  => 'Internal close button for the AAE Hotspot Point\'s lightbox.',
				'icon'         => 'eicon-close',
				'is_pro'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'hotspot close', 'internal' ],
				'category'     => 'general',
				'order'        => 24,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-hotspot-lightbox' => [
				'label'        => 'Hotspot Lightbox (Internal)',
				'description'  => 'Internal dark backdrop + centering frame the AAE Hotspot Point\'s content is moved into for lightbox display.',
				'icon'         => 'eicon-lightbox-expand',
				'is_pro'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'hotspot lightbox', 'internal' ],
				'category'     => 'general',
				'order'        => 25,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-flip-box-title' => [
				'label'        => 'Flip Box Title (Internal)',
				'description'  => 'Internal face title used by the AAE Flip Box front/back faces.',
				'icon'         => 'eicon-t-letter-bold',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'flip title', 'internal' ],
				'category'     => 'general',
				'order'        => 19,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-flip-box-text' => [
				'label'        => 'Flip Box Text (Internal)',
				'description'  => 'Internal face body copy used by the AAE Flip Box front/back faces.',
				'icon'         => 'eicon-paragraph',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'flip text', 'internal' ],
				'category'     => 'general',
				'order'        => 20,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-site-logo' => [
				'label'        => 'Site Logo',
				'description'  => 'Displays the site logo with a configurable link — wraps a native Elementor image child so each piece is independently styleable.',
				'icon'         => 'eicon-site-logo',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'site logo',
					'logo',
					'branding',
					'atomic',
					'header',
				],
				'category'     => 'header-footer',
				'order'        => 17,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-video-mask' => [
				'label'        => 'Video Mask',
				'description'  => 'A click-triggered masked video player with a customisable toggle button — icon and label are independent atomic children.',
				'icon'         => 'eicon-youtube',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'video',
					'mask',
					'play',
					'atomic',
					'shape',
				],
				'category'     => 'video',
				'order'        => 18,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-video-mask-btn' => [
				'is_internal'  => true,
				'label'        => 'Video Mask Button (Internal)',
				'description'  => 'Internal button container for Video Mask. Positioned via the native Style panel.',
				'icon'         => 'eicon-button',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [ 'video mask button', 'internal' ],
				'category'     => 'general',
				'order'        => 19,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-btn' => [
				'label'        => 'Button',
				'description'  => 'A very basic open button container — no style presets, just a link wrapper you can fill with any nested elements.',
				'icon'         => 'wcf-icon-Button',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'button',
					'basic button',
					'template',
					'container',
					'atomic',
				],
				'category'     => 'general',
				'order'        => 21,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-btn-pro' => [
				'label'        => 'Button Pro',
				// Was a copy of aae-a-btn's description; the accurate text lived on
				// the duplicate 'aae-a-button-pro' entry that has now been removed.
				'description'  => 'Advanced button widget with 8 GSAP-powered hover styles: ripple, text flip, border divide, group swap, shadow, outline pill, and slide fill.',
				'icon'         => 'wcf-icon-Button',
				'is_pro'       => true,
				'badge_only'       => true,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'button',
					'basic button',
					'template',
					'container',
					'atomic',
					'pro',
				],
				'category'     => 'general',
				'order'        => 22,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-video' => [
				'label'        => 'Video',
				'description'  => 'A simple video player card with a centered play button and a standard custom controls bar — supports YouTube, Vimeo, a hosted URL, and Media Library uploads.',
				'icon'         => 'eicon-video-playlist',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'video',
					'youtube',
					'vimeo',
					'player',
					'media',
					'atomic',
				],
				'category'     => 'video',
				'order'        => 19,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-video-player' => [
				'label'        => 'Video — Player',
				'description'  => 'Internal video-engine sub-element used by the AAE Video widget.',
				'icon'         => 'eicon-video-playlist',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'video', 'player', 'internal' ],
				'category'     => 'video',
				'order'        => 20,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-video-playbtn' => [
				'label'        => 'Video — Play Button',
				'description'  => 'Internal play-button trigger used by the AAE Video widget.',
				'icon'         => 'eicon-play',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'is_internal'  => true,
				'default'      => true,
				'keywords'     => [ 'video', 'play', 'button', 'internal' ],
				'category'     => 'video',
				'order'        => 21,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-curved-text' => [
				'label'        => 'Curved Text',
				'description'  => 'A spinning circular badge — curved rotating text or a rotating image, with a static icon on top. Purely decorative, no JS runtime.',
				'icon'         => 'eicon-dot-circle-o',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'curved',
					'text',
					'rotate',
					'rotating',
					'spin',
					'spinner',
					'circle',
					'circular',
					'badge',
					'atomic',
				],
				'category'     => 'general',
				'order'        => 22,
				'demo_url'     => '',
				'doc_url'      => '',
			],

			'aae-a-google-maps' => [
				'label'        => 'Google Maps',
				'description'  => 'An embedded Google map placed by address, with a zoom level. Reuses the API key from Elementor > Settings > Integrations, and falls back to the keyless embed when none is set.',
				'icon'         => 'eicon-google-maps',
				'is_pro'       => false,
				'is_extension' => false,
				'is_upcoming'  => false,
				'default'      => true,
				'keywords'     => [
					'google',
					'map',
					'maps',
					'embed',
					'location',
					'address',
					'atomic',
				],
				'category'     => 'general',
				'order'        => 23,
				'demo_url'     => '',
				'doc_url'      => '',
			],

		];
