<?php
/**
 * The pre-4.2 CLASS names, mapped to the ones the plugin declares now.
 *
 * 4.2.0 renamed every class whose own name carried one of the plugin's two
 * three-letter families (`AAE_`, `WCF_`) to the four-plus-character
 * `Aaeaddon_` prefix WordPress.org asked for, keeping the rest of the name:
 * `AAE_A_Loop_Grid` became `Aaeaddon_A_Loop_Grid`, `WCF_Theme_Builder` became
 * `Aaeaddon_Theme_Builder`. Together with `namespace-alias.php` — the file
 * that requires this one — that makes the rename invisible to the paid add-on
 * and to any site snippet or child theme that named a class of ours.
 *
 * ONE pair is not a straight strip. `AAE_Post_Handler_Trait` and
 * `WCF_Post_Handler_Trait` are two near-identical copies in the SAME
 * namespace, so both cannot become `Aaeaddon_Post_Handler_Trait`. The one the
 * add-on builds on (and free's own Loop Grid widget uses) keeps the plain
 * name; the older copy, used only by four v3 widgets here and by nothing in
 * the add-on, is `Aaeaddon_Post_Handler_Legacy_Trait`. Merging them would be a
 * behaviour change and is deliberately not attempted.
 *
 * This file and `namespace-alias.php` are the only two places in the plugin
 * where a pre-4.2 name appears. Read as a plain array — no autoload, no class
 * — so the uninstall hook and the test suite can require it directly.
 *
 * @package Wealcoder\AnimationAddons
 * @since   4.2.0
 */

defined( 'ABSPATH' ) || die();

// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals -- pre-4.2 names being aliased.
return array(
	'AAE_ACF_Field_Control'              => 'Aaeaddon_ACF_Field_Control',
	'AAE_A_Accordion'                    => 'Aaeaddon_A_Accordion',
	'AAE_A_Accordion_Item'               => 'Aaeaddon_A_Accordion_Item',
	'AAE_A_Advance_Portfolio'            => 'Aaeaddon_A_Advance_Portfolio',
	'AAE_A_Advanced_Heading'             => 'Aaeaddon_A_Advanced_Heading',
	'AAE_A_Btn'                          => 'Aaeaddon_A_Btn',
	'AAE_A_Btn_Hover_Style_Control'      => 'Aaeaddon_A_Btn_Hover_Style_Control',
	'AAE_A_Countdown'                    => 'Aaeaddon_A_Countdown',
	'AAE_A_Countdown_Unit'               => 'Aaeaddon_A_Countdown_Unit',
	'AAE_A_Counter'                      => 'Aaeaddon_A_Counter',
	'AAE_A_Curved_Text'                  => 'Aaeaddon_A_Curved_Text',
	'AAE_A_Flip_Box'                     => 'Aaeaddon_A_Flip_Box',
	'AAE_A_Flip_Box_Back'                => 'Aaeaddon_A_Flip_Box_Back',
	'AAE_A_Flip_Box_Front'               => 'Aaeaddon_A_Flip_Box_Front',
	'AAE_A_Flip_Box_Text'                => 'Aaeaddon_A_Flip_Box_Text',
	'AAE_A_Flip_Box_Title'               => 'Aaeaddon_A_Flip_Box_Title',
	'AAE_A_Form'                         => 'Aaeaddon_A_Form',
	'AAE_A_Form_Actions_Control'         => 'Aaeaddon_A_Form_Actions_Control',
	'AAE_A_Form_Calculation'             => 'Aaeaddon_A_Form_Calculation',
	'AAE_A_Form_Checkbox'                => 'Aaeaddon_A_Form_Checkbox',
	'AAE_A_Form_Country'                 => 'Aaeaddon_A_Form_Country',
	'AAE_A_Form_Error_Message'           => 'Aaeaddon_A_Form_Error_Message',
	'AAE_A_Form_Field_Error'             => 'Aaeaddon_A_Form_Field_Error',
	'AAE_A_Form_File'                    => 'Aaeaddon_A_Form_File',
	'AAE_A_Form_Input'                   => 'Aaeaddon_A_Form_Input',
	'AAE_A_Form_Label'                   => 'Aaeaddon_A_Form_Label',
	'AAE_A_Form_Message'                 => 'Aaeaddon_A_Form_Message',
	'AAE_A_Form_Next'                    => 'Aaeaddon_A_Form_Next',
	'AAE_A_Form_Password'                => 'Aaeaddon_A_Form_Password',
	'AAE_A_Form_Prev'                    => 'Aaeaddon_A_Form_Prev',
	'AAE_A_Form_Radio'                   => 'Aaeaddon_A_Form_Radio',
	'AAE_A_Form_Range'                   => 'Aaeaddon_A_Form_Range',
	'AAE_A_Form_Range_Group'             => 'Aaeaddon_A_Form_Range_Group',
	'AAE_A_Form_Range_Value'             => 'Aaeaddon_A_Form_Range_Value',
	'AAE_A_Form_Rating'                  => 'Aaeaddon_A_Form_Rating',
	'AAE_A_Form_Select'                  => 'Aaeaddon_A_Form_Select',
	'AAE_A_Form_Step'                    => 'Aaeaddon_A_Form_Step',
	'AAE_A_Form_Submit'                  => 'Aaeaddon_A_Form_Submit',
	'AAE_A_Form_Success_Message'         => 'Aaeaddon_A_Form_Success_Message',
	'AAE_A_Form_Textarea'                => 'Aaeaddon_A_Form_Textarea',
	'AAE_A_Google_Maps'                  => 'Aaeaddon_A_Google_Maps',
	'AAE_A_Hotspot_Close'                => 'Aaeaddon_A_Hotspot_Close',
	'AAE_A_Hotspot_Content'              => 'Aaeaddon_A_Hotspot_Content',
	'AAE_A_Hotspot_Lightbox'             => 'Aaeaddon_A_Hotspot_Lightbox',
	'AAE_A_Hotspot_Marker'               => 'Aaeaddon_A_Hotspot_Marker',
	'AAE_A_Hotspot_Point'                => 'Aaeaddon_A_Hotspot_Point',
	'AAE_A_Hotspots_Control'             => 'Aaeaddon_A_Hotspots_Control',
	'AAE_A_Icon_List'                    => 'Aaeaddon_A_Icon_List',
	'AAE_A_Icon_List_Item'               => 'Aaeaddon_A_Icon_List_Item',
	'AAE_A_Icon_List_Items_Control'      => 'Aaeaddon_A_Icon_List_Items_Control',
	'AAE_A_Image_Compare'                => 'Aaeaddon_A_Image_Compare',
	'AAE_A_Image_Hotspot'                => 'Aaeaddon_A_Image_Hotspot',
	'AAE_A_Items_Control'                => 'Aaeaddon_A_Items_Control',
	'AAE_A_Library_Document'             => 'Aaeaddon_A_Library_Document',
	'AAE_A_Loop_Arrow'                   => 'Aaeaddon_A_Loop_Arrow',
	'AAE_A_Loop_Grid'                    => 'Aaeaddon_A_Loop_Grid',
	'AAE_A_Loop_Grid_Document'           => 'Aaeaddon_A_Loop_Grid_Document',
	'AAE_A_Loop_Grid_Slider'             => 'Aaeaddon_A_Loop_Grid_Slider',
	'AAE_A_Loop_Grid_Slider_Document'    => 'Aaeaddon_A_Loop_Grid_Slider_Document',
	'AAE_A_Loop_Item'                    => 'Aaeaddon_A_Loop_Item',
	'AAE_A_Loop_Layout'                  => 'Aaeaddon_A_Loop_Layout',
	'AAE_A_Loop_LoadMore'                => 'Aaeaddon_A_Loop_LoadMore',
	'AAE_A_Loop_Nav_Wrap'                => 'Aaeaddon_A_Loop_Nav_Wrap',
	'AAE_A_Loop_Next'                    => 'Aaeaddon_A_Loop_Next',
	'AAE_A_Loop_Number'                  => 'Aaeaddon_A_Loop_Number',
	'AAE_A_Loop_Numbers'                 => 'Aaeaddon_A_Loop_Numbers',
	'AAE_A_Loop_Pagination'              => 'Aaeaddon_A_Loop_Pagination',
	'AAE_A_Loop_Prev'                    => 'Aaeaddon_A_Loop_Prev',
	'AAE_A_Loop_Slide_Item'              => 'Aaeaddon_A_Loop_Slide_Item',
	'AAE_A_Loop_Slide_Pagination'        => 'Aaeaddon_A_Loop_Slide_Pagination',
	'AAE_A_Loop_Slide_Track'             => 'Aaeaddon_A_Loop_Slide_Track',
	'AAE_A_Menu'                         => 'Aaeaddon_A_Menu',
	'AAE_A_Menu_Drawer_Anchor_Prop_Type' => 'Aaeaddon_A_Menu_Drawer_Anchor_Prop_Type',
	'AAE_A_Menu_Drawer_Header_Anchor_Prop_Type' => 'Aaeaddon_A_Menu_Drawer_Header_Anchor_Prop_Type',
	'AAE_A_Menu_Dropdown_Items_Anchor_Prop_Type' => 'Aaeaddon_A_Menu_Dropdown_Items_Anchor_Prop_Type',
	'AAE_A_Menu_Dropdown_Panel_Anchor_Prop_Type' => 'Aaeaddon_A_Menu_Dropdown_Panel_Anchor_Prop_Type',
	'AAE_A_Menu_Hamburger_Anchor_Prop_Type' => 'Aaeaddon_A_Menu_Hamburger_Anchor_Prop_Type',
	'AAE_A_Menu_Items_Anchor_Prop_Type'  => 'Aaeaddon_A_Menu_Items_Anchor_Prop_Type',
	'AAE_A_Menu_Layout_Anchor_Prop_Type' => 'Aaeaddon_A_Menu_Layout_Anchor_Prop_Type',
	'AAE_A_Menu_Motion_Anchor_Prop_Type' => 'Aaeaddon_A_Menu_Motion_Anchor_Prop_Type',
	'AAE_A_Menu_Responsive'              => 'Aaeaddon_A_Menu_Responsive',
	'AAE_A_Menu_Toggle_Anchor_Prop_Type' => 'Aaeaddon_A_Menu_Toggle_Anchor_Prop_Type',
	'AAE_A_Mobile_Nav'                   => 'Aaeaddon_A_Mobile_Nav',
	'AAE_A_Mobile_Nav_Lifecycle_Control' => 'Aaeaddon_A_Mobile_Nav_Lifecycle_Control',
	'AAE_A_Nav'                          => 'Aaeaddon_A_Nav',
	'AAE_A_Nav_Companion_Sweep'          => 'Aaeaddon_A_Nav_Companion_Sweep',
	'AAE_A_Nav_Dropdown_Icon_Anchor_Prop_Type' => 'Aaeaddon_A_Nav_Dropdown_Icon_Anchor_Prop_Type',
	'AAE_A_Nav_Item'                     => 'Aaeaddon_A_Nav_Item',
	'AAE_A_Nav_Items_Control'            => 'Aaeaddon_A_Nav_Items_Control',
	'AAE_A_Nav_Menu_Sync'                => 'Aaeaddon_A_Nav_Menu_Sync',
	'AAE_A_Nav_Responsive'               => 'Aaeaddon_A_Nav_Responsive',
	'AAE_A_Nav_Sub_Item'                 => 'Aaeaddon_A_Nav_Sub_Item',
	'AAE_A_Nav_Sub_Items_Control'        => 'Aaeaddon_A_Nav_Sub_Items_Control',
	'AAE_A_Portfolio_Content'            => 'Aaeaddon_A_Portfolio_Content',
	'AAE_A_Portfolio_Date'               => 'Aaeaddon_A_Portfolio_Date',
	'AAE_A_Portfolio_Item'               => 'Aaeaddon_A_Portfolio_Item',
	'AAE_A_Portfolio_List'               => 'Aaeaddon_A_Portfolio_List',
	'AAE_A_Portfolio_Preset_Picker_Control' => 'Aaeaddon_A_Portfolio_Preset_Picker_Control',
	'AAE_A_Portfolio_Title'              => 'Aaeaddon_A_Portfolio_Title',
	'AAE_A_Post_Card'                    => 'Aaeaddon_A_Post_Card',
	'AAE_A_Post_Content'                 => 'Aaeaddon_A_Post_Content',
	'AAE_A_Post_Excerpt'                 => 'Aaeaddon_A_Post_Excerpt',
	'AAE_A_Post_Image'                   => 'Aaeaddon_A_Post_Image',
	'AAE_A_Post_Pagination'              => 'Aaeaddon_A_Post_Pagination',
	'AAE_A_Post_Pagination_Next'         => 'Aaeaddon_A_Post_Pagination_Next',
	'AAE_A_Post_Pagination_Prev'         => 'Aaeaddon_A_Post_Pagination_Prev',
	'AAE_A_Post_Pagination_Preview'      => 'Aaeaddon_A_Post_Pagination_Preview',
	'AAE_A_Post_Pagination_Preview_Author' => 'Aaeaddon_A_Post_Pagination_Preview_Author',
	'AAE_A_Post_Pagination_Preview_Category' => 'Aaeaddon_A_Post_Pagination_Preview_Category',
	'AAE_A_Post_Pagination_Preview_Date' => 'Aaeaddon_A_Post_Pagination_Preview_Date',
	'AAE_A_Post_Pagination_Preview_Excerpt' => 'Aaeaddon_A_Post_Pagination_Preview_Excerpt',
	'AAE_A_Post_Pagination_Preview_Image' => 'Aaeaddon_A_Post_Pagination_Preview_Image',
	'AAE_A_Post_Pagination_Preview_Title' => 'Aaeaddon_A_Post_Pagination_Preview_Title',
	'AAE_A_Post_Title'                   => 'Aaeaddon_A_Post_Title',
	'AAE_A_Posts'                        => 'Aaeaddon_A_Posts',
	'AAE_A_Preset_Picker_Control'        => 'Aaeaddon_A_Preset_Picker_Control',
	'AAE_A_Progressbar'                  => 'Aaeaddon_A_Progressbar',
	'AAE_A_Progressbar_Dot'              => 'Aaeaddon_A_Progressbar_Dot',
	'AAE_A_Progressbar_Fill'             => 'Aaeaddon_A_Progressbar_Fill',
	'AAE_A_Progressbar_Label'            => 'Aaeaddon_A_Progressbar_Label',
	'AAE_A_Progressbar_Track'            => 'Aaeaddon_A_Progressbar_Track',
	'AAE_A_Search_Field'                 => 'Aaeaddon_A_Search_Field',
	'AAE_A_Search_Filter_Category'       => 'Aaeaddon_A_Search_Filter_Category',
	'AAE_A_Search_Filter_Date'           => 'Aaeaddon_A_Search_Filter_Date',
	'AAE_A_Search_Form'                  => 'Aaeaddon_A_Search_Form',
	'AAE_A_Search_Input'                 => 'Aaeaddon_A_Search_Input',
	'AAE_A_Search_Panel'                 => 'Aaeaddon_A_Search_Panel',
	'AAE_A_Search_Query'                 => 'Aaeaddon_A_Search_Query',
	'AAE_A_Search_Results'               => 'Aaeaddon_A_Search_Results',
	'AAE_A_Search_Submit'                => 'Aaeaddon_A_Search_Submit',
	'AAE_A_Search_Toggle'                => 'Aaeaddon_A_Search_Toggle',
	'AAE_A_Search_Toggle_Close'          => 'Aaeaddon_A_Search_Toggle_Close',
	'AAE_A_Search_Toggle_Open'           => 'Aaeaddon_A_Search_Toggle_Open',
	'AAE_A_Site_Logo'                    => 'Aaeaddon_A_Site_Logo',
	'AAE_A_Slide'                        => 'Aaeaddon_A_Slide',
	'AAE_A_Slide_Preset_Picker_Control'  => 'Aaeaddon_A_Slide_Preset_Picker_Control',
	'AAE_A_Slider'                       => 'Aaeaddon_A_Slider',
	'AAE_A_Slider_Counter'               => 'Aaeaddon_A_Slider_Counter',
	'AAE_A_Slider_Current'               => 'Aaeaddon_A_Slider_Current',
	'AAE_A_Slider_Divider'               => 'Aaeaddon_A_Slider_Divider',
	'AAE_A_Slider_Document'              => 'Aaeaddon_A_Slider_Document',
	'AAE_A_Slider_Dot'                   => 'Aaeaddon_A_Slider_Dot',
	'AAE_A_Slider_Indicators'            => 'Aaeaddon_A_Slider_Indicators',
	'AAE_A_Slider_Nav_Next'              => 'Aaeaddon_A_Slider_Nav_Next',
	'AAE_A_Slider_Nav_Prev'              => 'Aaeaddon_A_Slider_Nav_Prev',
	'AAE_A_Slider_Pagination'            => 'Aaeaddon_A_Slider_Pagination',
	'AAE_A_Slider_Percentage'            => 'Aaeaddon_A_Slider_Percentage',
	'AAE_A_Slider_Progress'              => 'Aaeaddon_A_Slider_Progress',
	'AAE_A_Slider_Progress_Fill'         => 'Aaeaddon_A_Slider_Progress_Fill',
	'AAE_A_Slider_Total'                 => 'Aaeaddon_A_Slider_Total',
	'AAE_A_Slider_Track'                 => 'Aaeaddon_A_Slider_Track',
	'AAE_A_Slides_Control'               => 'Aaeaddon_A_Slides_Control',
	'AAE_A_Social_Share'                 => 'Aaeaddon_A_Social_Share',
	'AAE_A_Social_Share_Item'            => 'Aaeaddon_A_Social_Share_Item',
	'AAE_A_Social_Share_Item_Icon'       => 'Aaeaddon_A_Social_Share_Item_Icon',
	'AAE_A_Social_Share_Item_Title'      => 'Aaeaddon_A_Social_Share_Item_Title',
	'AAE_A_Social_Share_Items_Control'   => 'Aaeaddon_A_Social_Share_Items_Control',
	'AAE_A_Timeline'                     => 'Aaeaddon_A_Timeline',
	'AAE_A_Timeline_Desc'                => 'Aaeaddon_A_Timeline_Desc',
	'AAE_A_Timeline_Item'                => 'Aaeaddon_A_Timeline_Item',
	'AAE_A_Timeline_Items_Control'       => 'Aaeaddon_A_Timeline_Items_Control',
	'AAE_A_Timeline_Number'              => 'Aaeaddon_A_Timeline_Number',
	'AAE_A_Timeline_Title'               => 'Aaeaddon_A_Timeline_Title',
	'AAE_A_Timeline_Year'                => 'Aaeaddon_A_Timeline_Year',
	'AAE_A_Toggle_Pane'                  => 'Aaeaddon_A_Toggle_Pane',
	'AAE_A_Toggle_Pane_Desc'             => 'Aaeaddon_A_Toggle_Pane_Desc',
	'AAE_A_Toggle_Pane_Title'            => 'Aaeaddon_A_Toggle_Pane_Title',
	'AAE_A_Toggle_Switcher'              => 'Aaeaddon_A_Toggle_Switcher',
	'AAE_A_Toggle_Switcher_Knob'         => 'Aaeaddon_A_Toggle_Switcher_Knob',
	'AAE_A_Toggle_Switcher_Label'        => 'Aaeaddon_A_Toggle_Switcher_Label',
	'AAE_A_Toggle_Switcher_Tab'          => 'Aaeaddon_A_Toggle_Switcher_Tab',
	'AAE_A_Toggle_Switcher_Tablist'      => 'Aaeaddon_A_Toggle_Switcher_Tablist',
	'AAE_A_Toggle_Switcher_Tabs'         => 'Aaeaddon_A_Toggle_Switcher_Tabs',
	'AAE_A_Toggle_Switcher_Track'        => 'Aaeaddon_A_Toggle_Switcher_Track',
	'AAE_A_Video'                        => 'Aaeaddon_A_Video',
	'AAE_A_Video_Mask'                   => 'Aaeaddon_A_Video_Mask',
	'AAE_A_Video_Mask_Btn'               => 'Aaeaddon_A_Video_Mask_Btn',
	'AAE_A_Video_PlayBtn'                => 'Aaeaddon_A_Video_PlayBtn',
	'AAE_A_Video_Player'                 => 'Aaeaddon_A_Video_Player',
	'AAE_Admin_Page_Importer'            => 'Aaeaddon_Admin_Page_Importer',
	'AAE_Advanced_Heading_Migration'     => 'Aaeaddon_Advanced_Heading_Migration',
	'AAE_Color_Control'                  => 'Aaeaddon_Color_Control',
	'AAE_Fonts'                          => 'Aaeaddon_Fonts',
	'AAE_Inline_Text_Control'            => 'Aaeaddon_Inline_Text_Control',
	'AAE_Loop_Builder_Integration'       => 'Aaeaddon_Loop_Builder_Integration',
	'AAE_Nested_Slider_Trait'            => 'Aaeaddon_Nested_Slider_Trait',
	'AAE_Notice_Control'                 => 'Aaeaddon_Notice_Control',
	'AAE_Post_Handler_Trait'             => 'Aaeaddon_Post_Handler_Trait',
	'AAE_Query_Chips_Control'            => 'Aaeaddon_Query_Chips_Control',
	'AAE_Rich_Text_Prop_Type'            => 'Aaeaddon_Rich_Text_Prop_Type',
	// Four names that carried the family WITHOUT the underscore and slipped
	// the 4.2.0 codemod; renamed 2026-09-17 with the rest of the prefix work.
	'AAEImporter'                        => 'Aaeaddon_Content_Importer',
	'AAEAddon_Importer'                  => 'Aaeaddon_Template_Importer',
	'AAEAddon_Row_Actions'               => 'Aaeaddon_Row_Actions',
	'WCFAddon_BlackList_Notice'          => 'Aaeaddon_BlackList_Notice',
	'WCF_ADDONS_Plugin'                  => 'Aaeaddon_Plugin',
	'WCF_Admin_Init'                     => 'Aaeaddon_Admin_Init',
	'WCF_Button_Trait'                   => 'Aaeaddon_Button_Trait',
	'WCF_Custom_CSS'                     => 'Aaeaddon_Custom_CSS',
	'WCF_Extension_Widgets_Trait'        => 'Aaeaddon_Extension_Widgets_Trait',
	'WCF_Menu_Walker'                    => 'Aaeaddon_Menu_Walker',
	'WCF_Plugin_Installer'               => 'Aaeaddon_Plugin_Installer',
	'WCF_Post_Handler_Trait'             => 'Aaeaddon_Post_Handler_Legacy_Trait',
	'WCF_Post_Query_Trait'               => 'Aaeaddon_Post_Query_Trait',
	'WCF_Setup_Wizard_Init'              => 'Aaeaddon_Setup_Wizard_Init',
	'WCF_Slider_Trait'                   => 'Aaeaddon_Slider_Trait',
	'WCF_Starter_Animations'             => 'Aaeaddon_Starter_Animations',
	'WCF_Theme_Builder'                  => 'Aaeaddon_Theme_Builder',
);
// phpcs:enable WordPress.NamingConventions.PrefixAllGlobals
