<?php

namespace Wealcoder\AnimationAddons;

defined( 'ABSPATH' ) || exit;

use Elementor\Core\Common\Modules\Ajax\Module as Ajax;

class Layout_Import_Api {
	public function __construct() {
		add_action( 'elementor/ajax/register_actions', array( $this, 'register_ajax_actions' ) );
	}

	public function register_ajax_actions( Ajax $ajax ) {
		$ajax->register_ajax_action(
			'get_wcf_template_data',
			function ( $data ) {
				if ( ! current_user_can( 'edit_posts' ) ) {
					throw new \Exception( 'Access Denied' );
				}

				if ( ! empty( $data['editor_post_id'] ) ) {
					$editor_post_id = absint( $data['editor_post_id'] );

					if ( ! get_post( $editor_post_id ) ) {
						throw new \Exception( esc_html__( 'Post not found', 'animation-addons-for-elementor' ) );
					}

					\Elementor\Plugin::instance()->db->switch_to_post( $editor_post_id );
				}
		
				if ( empty( $data['template_id'] ) ) {
					throw new \Exception( esc_html__( 'Template id missing', 'animation-addons-for-elementor' ) );
				}
				
				$result = $this->get_template_data( $data );

				return $result;
			}
		);

		/*
		 * The server half of a V4 (atomic) BLOCK insert. The client has the
		 * block's file already (the block server relays the Save-as-Template
		 * export verbatim); what it cannot do from the browser is done here,
		 * in this order:
		 *
		 *  1. fresh element ids — and, through Elementor's replace_id filter,
		 *     fresh LOCAL style ids (Library_Source::replace_ids());
		 *  2. images / SVGs / Lotties copied into this site's media library,
		 *     deduped by source hash (Atomic_Image_Localize::localize_elements());
		 *  3. the AAE widgets and extensions the block uses switched on, when
		 *     the user may change the site's widget set — otherwise reported as
		 *     `missing` so the client can say who has to.
		 *
		 * The global classes and variables are NOT touched here: the client
		 * hands them to Elementor's own `process_global_styles`, whose result
		 * the editor's Classes/Variables panels pick up without a reload. A
		 * PHP-side write would leave those panels stale.
		 */
		$ajax->register_ajax_action(
			'aaeaddon_prepare_v4_block',
			function ( $data ) {
				if ( ! current_user_can( 'edit_posts' ) ) {
					throw new \Exception( 'Access Denied' );
				}

				if ( ! empty( $data['editor_post_id'] ) ) {
					$editor_post_id = absint( $data['editor_post_id'] );

					if ( ! get_post( $editor_post_id ) ) {
						throw new \Exception( esc_html__( 'Post not found', 'animation-addons-for-elementor' ) );
					}

					\Elementor\Plugin::instance()->db->switch_to_post( $editor_post_id );
				}

				return $this->prepare_v4_block( $data );
			}
		);

		/*
		 * What a template (V3 or V4, block or page) NEEDS from this site that
		 * is switched off, before anything is inserted. The client shows the
		 * list — a section whose AAE widgets are off used to insert with those
		 * widgets silently dropped (get_elements_raw_data() skips any type not
		 * registered) — and, for a user who may change the widget set, offers
		 * to switch them on through `aaeaddon_enable_template_widgets`.
		 * Read-only: nothing is written here.
		 */
		$ajax->register_ajax_action(
			'aaeaddon_template_dependencies',
			function ( $data ) {
				if ( ! current_user_can( 'edit_posts' ) ) {
					throw new \Exception( 'Access Denied' );
				}

				return $this->template_dependencies( $data );
			}
		);

		/*
		 * The enable half of the dialog above. Widgets go on through the same
		 * writers the dashboard uses; the editor then saves and reloads so the
		 * newly registered types reach elementor.config.
		 */
		$ajax->register_ajax_action(
			'aaeaddon_enable_template_widgets',
			function ( $data ) {
				if ( ! current_user_can( 'manage_options' ) ) {
					throw new \Exception( 'Access Denied' );
				}

				return $this->enable_template_widgets( $data );
			}
		);

		/*
		 * After the client has run Elementor's `process_global_styles` for a
		 * block: a variable it CREATED (keep_create) is written to the kit but
		 * the kit's stylesheet (`post-<kit>.css`, where every `--variable` is
		 * declared) is not regenerated by that path — measured: the inserted
		 * block's rule read `var(--DUP_background-primary2)` while the kit CSS
		 * still declared only the variables it had before, so the background
		 * rendered transparent until something else cleared the cache. The
		 * Variables Manager's own REST save calls `files_manager->clear_cache()`
		 * for exactly this; so does this, and only when a variable changed.
		 */
		$ajax->register_ajax_action(
			'aaeaddon_v4_block_inserted',
			function ( $data ) {
				if ( ! current_user_can( 'edit_posts' ) ) {
					throw new \Exception( 'Access Denied' );
				}

				if ( ! empty( $data['variables'] ) && isset( \Elementor\Plugin::$instance->files_manager ) ) {
					\Elementor\Plugin::$instance->files_manager->clear_cache();
				}

				return [ 'ok' => true ];
			}
		);
	}

	/**
	 * @param array $args `content` — the block's elements array. `media` —
	 *                    'vector' keeps photos on the demo server (Live
	 *                    Paste's "Keep demo image links"); anything else, or
	 *                    absent, copies them as before.
	 * @return array{content:array,enabled:string[],enabled_extensions:string[],missing:string[],localized:array}
	 */
	private function prepare_v4_block( array $args ): array {
		$content = $args['content'] ?? null;

		if ( is_string( $content ) ) {
			$content = json_decode( $content, true );
		}

		if ( ! is_array( $content ) || empty( $content ) ) {
			throw new \Exception( esc_html__( 'Template does not have any content', 'animation-addons-for-elementor' ) );
		}

		// A single root arrives as an object; the walkers want a list.
		if ( isset( $content['elType'] ) ) {
			$content = [ $content ];
		}

		$source  = new Library_Source();
		$content = $source->replace_ids( array_values( $content ) );
		$content = $this->drop_unknown_dynamic_tags( $content );

		$localized = [ 'images' => 0, 'lottie' => 0, 'reused' => 0, 'failed' => 0, 'stopped' => false ];

		if ( ! class_exists( '\Wealcoder\AnimationAddons\Admin\Base\Atomic_Image_Localize' ) ) {
			$file = AAEADDON_PATH . 'inc/admin/atomic-image-localize.php';
			if ( file_exists( $file ) ) {
				require_once $file;
			}
		}

		if ( class_exists( '\Wealcoder\AnimationAddons\Admin\Base\Atomic_Image_Localize' ) ) {
			$photos  = 'vector' !== ( $args['media'] ?? 'all' );
			$result  = \Wealcoder\AnimationAddons\Admin\Base\Atomic_Image_Localize::localize_elements( $content, true, null, true, $photos );
			$content = $result['elements'];
			unset( $result['elements'] );
			$localized = $result;
		}

		$enabled = [ 'widgets' => [], 'extensions' => [] ];
		$missing = [];

		if ( class_exists( '\Wealcoder\AnimationAddons\AtomicWidgets\Atomic_Admin' ) ) {
			$rows      = [ (string) wp_json_encode( $content ) ];
			$can_write = current_user_can( 'manage_options' );
			$used      = \Wealcoder\AnimationAddons\AtomicWidgets\Atomic_Admin::enable_used_atomic_in_rows( $rows, $can_write );

			if ( $can_write ) {
				$enabled = $used;
			} else {
				$missing = $used['widgets'];
			}
		}

		return [
			'content'            => $content,
			'enabled'            => $enabled['widgets'],
			'enabled_extensions' => $enabled['extensions'],
			'missing'            => $missing,
			'localized'          => $localized,
		];
	}

	/**
	 * Remove atomic dynamic values whose tag is not registered on this site.
	 *
	 * A block made on another site can carry a dynamic tag this site does not
	 * have (e.g. a button link bound to `aae-internal-url` with the source
	 * site's post id). The insert works, but Elementor refuses to SAVE it:
	 * Dynamic_Prop_Type::validate_value() fails on an unknown tag —
	 * "Settings validation failed. link: invalid_value". Dropping the key
	 * falls back to the prop's default (a link without a destination is
	 * valid), so the document saves.
	 *
	 * @param array $node Elements list, element, settings or any nested value.
	 * @return array
	 */
	private function drop_unknown_dynamic_tags( array $node ): array {
		$module = '\Elementor\Modules\AtomicWidgets\DynamicTags\Dynamic_Tags_Module';
		if ( ! class_exists( $module ) ) {
			return $node;
		}

		$registry = $module::instance()->registry;

		foreach ( $node as $key => $value ) {
			if ( ! is_array( $value ) ) {
				continue;
			}

			if ( 'dynamic' === ( $value['$$type'] ?? null ) ) {
				$name = $value['value']['name'] ?? '';
				if ( ! is_string( $name ) || '' === $name || ! $registry->get_tag( $name ) ) {
					unset( $node[ $key ] );
				}
				continue;
			}

			$node[ $key ] = $this->drop_unknown_dynamic_tags( $value );
		}

		return $node;
	}

	/**
	 * Normalise the `content` a client sends: a JSON string or an array, a
	 * single root object or a list of roots.
	 *
	 * @param mixed $content
	 * @return array List of root elements (possibly empty).
	 */
	private function content_list( $content ): array {
		if ( is_string( $content ) ) {
			$content = json_decode( $content, true );
		}

		if ( ! is_array( $content ) ) {
			return [];
		}

		if ( isset( $content['elType'] ) ) {
			$content = [ $content ];
		}

		return array_values( $content );
	}

	/**
	 * @param array $args `content` — the template's elements; `builder` — v3|v4.
	 * @return array{
	 *   builder:string,
	 *   widgets:array<int,array{slug:string,label:string}>,
	 *   extensions:array<int,array{slug:string,label:string}>,
	 *   missing:array<int,array{slug:string,label:string}>,
	 *   can_enable:bool
	 * } `widgets`/`extensions` are switched off and can be switched on;
	 *   `missing` are AAE types this site does not have at all (a Pro widget
	 *   with Pro absent) and will be dropped by the insert.
	 */
	private function template_dependencies( array $args ): array {
		$content = $this->content_list( $args['content'] ?? null );
		$builder = ( isset( $args['builder'] ) && 'v4' === $args['builder'] ) ? 'v4' : 'v3';

		$out = [
			'builder'    => $builder,
			'widgets'    => [],
			'extensions' => [],
			'missing'    => [],
			'can_enable' => current_user_can( 'manage_options' ),
		];

		if ( empty( $content ) ) {
			return $out;
		}

		$json = (string) wp_json_encode( $content );

		if ( 'v4' === $builder ) {
			if ( ! class_exists( '\Wealcoder\AnimationAddons\AtomicWidgets\Atomic_Admin' ) ) {
				return $out;
			}

			$atomic   = \Wealcoder\AnimationAddons\AtomicWidgets\Atomic::instance();
			$registry = $atomic->get_widgets_registry();
			$exts     = $atomic->extensions_registry();
			$parents  = $atomic->widget_parent_map();
			$needed   = \Wealcoder\AnimationAddons\AtomicWidgets\Atomic_Admin::enable_used_atomic_in_rows( [ $json ], false );

			foreach ( $needed['widgets'] as $slug ) {
				$out['widgets'][] = [
					'slug'  => $slug,
					'label' => (string) ( $registry[ $slug ]['label'] ?? $slug ),
				];
			}

			foreach ( $needed['extensions'] as $slug ) {
				$out['extensions'][] = [
					'slug'  => $slug,
					'label' => (string) ( $exts[ $slug ]['label'] ?? $slug ),
				];
			}

			// An AAE atomic type this site's registry does not know at all —
			// a Pro widget on a site without Pro. The enabler skips those; the
			// insert cannot render them.
			if ( preg_match_all( '/"(?:widgetType|elType)":"e-(aae-a-[a-z0-9-]+)"/', $json, $m ) ) {
				$seen = [];
				foreach ( $m[1] as $slug ) {
					$root = $parents[ $slug ] ?? $slug;
					if ( isset( $registry[ $root ] ) || isset( $seen[ $root ] ) ) {
						continue;
					}
					$seen[ $root ]    = true;
					$out['missing'][] = [
						'slug'  => $root,
						'label' => $root,
					];
				}
			}

			return $out;
		}

		// V3: a widget saves as its Elementor NAME (`wcf--title`); the
		// dashboard switch is keyed by SLUG (`animated-title`). The map reads
		// the widget files, so a name it does not know is a widget this site
		// has no file for — a Pro widget with Pro absent.
		if ( ! class_exists( '\Wealcoder\AnimationAddons\AnimationSettings\Animation_Settings' ) ) {
			return $out;
		}

		$map    = \Wealcoder\AnimationAddons\AnimationSettings\Animation_Settings::widget_name_to_slug_map();
		$active = get_option( 'aaeaddon_save_widgets' );
		$active = is_array( $active ) ? $active : [];
		$index  = function_exists( 'aaeaddon_config_index' ) ? aaeaddon_config_index( 'widgets' ) : [];
		$seen   = [];

		if ( preg_match_all( '/"widgetType":"([a-zA-Z0-9_-]+)"/', $json, $m ) ) {
			foreach ( array_unique( $m[1] ) as $name ) {
				if ( isset( $map[ $name ] ) ) {
					$slug = $map[ $name ];
					if ( isset( $active[ $slug ] ) || isset( $seen[ $slug ] ) ) {
						continue;
					}
					$seen[ $slug ]    = true;
					$out['widgets'][] = [
						'slug'  => $slug,
						'label' => (string) ( $index[ $slug ]['label'] ?? $slug ),
					];
				} elseif ( preg_match( '/^(?:wcf|aae)(?:--|-)/', $name ) ) {
					if ( isset( $seen[ $name ] ) ) {
						continue;
					}
					$seen[ $name ]    = true;
					$out['missing'][] = [
						'slug'  => $name,
						'label' => $name,
					];
				}
			}
		}

		return $out;
	}

	/**
	 * @param array $args `builder` — v3|v4; `widgets`, `extensions` — slugs.
	 * @return array{enabled:string[],enabled_extensions:string[]}
	 */
	private function enable_template_widgets( array $args ): array {
		$builder = ( isset( $args['builder'] ) && 'v4' === $args['builder'] ) ? 'v4' : 'v3';
		$widgets = array_values( array_unique( array_filter( array_map( 'sanitize_key', (array) ( $args['widgets'] ?? [] ) ) ) ) );
		$exts    = array_values( array_unique( array_filter( array_map( 'sanitize_key', (array) ( $args['extensions'] ?? [] ) ) ) ) );

		$enabled = [ 'enabled' => [], 'enabled_extensions' => [] ];

		if ( 'v4' === $builder ) {
			if ( ! class_exists( '\Wealcoder\AnimationAddons\AtomicWidgets\Atomic_Admin' ) ) {
				return $enabled;
			}

			$atomic = \Wealcoder\AnimationAddons\AtomicWidgets\Atomic::instance();

			if ( ! empty( $widgets ) ) {
				$registry = $atomic->get_widgets_registry();
				$saved    = $atomic->get_saved_options();
				foreach ( $widgets as $slug ) {
					if ( isset( $registry[ $slug ] ) && ! isset( $saved[ $slug ] ) ) {
						$saved[ $slug ]       = true;
						$enabled['enabled'][] = $slug;
					}
				}
				if ( ! empty( $enabled['enabled'] ) ) {
					\Wealcoder\AnimationAddons\AtomicWidgets\Atomic_Admin::write_widget_option( $saved );
				}
			}

			if ( ! empty( $exts ) ) {
				$registry = $atomic->extensions_registry();
				$saved    = $atomic->get_saved_extension_options();
				foreach ( $exts as $slug ) {
					if ( isset( $registry[ $slug ] ) && ! isset( $saved[ $slug ] ) ) {
						$saved[ $slug ]                  = true;
						$enabled['enabled_extensions'][] = $slug;
					}
				}
				if ( ! empty( $enabled['enabled_extensions'] ) ) {
					\Wealcoder\AnimationAddons\AtomicWidgets\Atomic_Admin::write_extension_option( $saved );
				}
			}

			return $enabled;
		}

		if ( empty( $widgets ) || ! function_exists( 'aaeaddon_config_index' ) ) {
			return $enabled;
		}

		// Same row and shape maybe_enable_used_v3_widgets() writes: slug => true.
		$index = aaeaddon_config_index( 'widgets' );
		$saved = get_option( 'aaeaddon_save_widgets' );
		$saved = is_array( $saved ) ? $saved : [];

		foreach ( $widgets as $slug ) {
			if ( isset( $index[ $slug ] ) && ! isset( $saved[ $slug ] ) ) {
				$saved[ $slug ]       = true;
				$enabled['enabled'][] = $slug;
			}
		}

		if ( ! empty( $enabled['enabled'] ) ) {
			update_option( 'aaeaddon_save_widgets', $saved );
		}

		return $enabled;
	}

	private function get_template_data( array $args ) {
		$source = new Library_Source();
		$data   = $source->get_data( $args );       
		return $data;
	}
}

new Layout_Import_Api();
